/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package html.parsing.stock.news;

import html.parsing.stock.JsoupChangeImageElementsAttribute;
import html.parsing.stock.StockUtil;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.StyleSheet;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;

/**
 *
 * @author banks
 */
public class NewsReader extends javax.swing.JFrame {

    java.util.logging.Logger logger = null;

    /**
     * Creates new form NewJFrame1
     */
    public NewsReader() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton25 = new javax.swing.JRadioButton();
        jRadioButton26 = new javax.swing.JRadioButton();
        jRadioButton27 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        urlLbl = new javax.swing.JLabel();
        textFieldPopupMenuPanel1 = new html.parsing.stock.TextFieldPopupMenuPanel();
        jPanel9 = new javax.swing.JPanel();
        executeBtn = new javax.swing.JButton();
        extractImgBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        newsTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel8 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("웹페이지 추출");
        setMinimumSize(new java.awt.Dimension(500, 250));
        setSize(new java.awt.Dimension(800, 600));

        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel3.setMinimumSize(new java.awt.Dimension(429, 150));
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setLayout(new java.awt.GridLayout(5, 5));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("머니 투데이");
        jRadioButton1.setActionCommand("MT");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton1);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("시사인");
        jRadioButton2.setActionCommand("SSI");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton2);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("국민일보");
        jRadioButton3.setActionCommand("KMIB");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton3);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("경향신문");
        jRadioButton4.setActionCommand("KHSM");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton4);

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("한겨레");
        jRadioButton5.setActionCommand("HKR");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton5);

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("중앙일보");
        jRadioButton6.setActionCommand("JAIB");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton6);

        buttonGroup1.add(jRadioButton21);
        jRadioButton21.setText("Chosun Biz");
        jRadioButton21.setActionCommand("CHOSUNBIZ");
        jRadioButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton21ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton21);

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setText("조선일보");
        jRadioButton7.setActionCommand("CSIB");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton7);

        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setText("한국일보");
        jRadioButton8.setActionCommand("HKIB");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton8);

        buttonGroup1.add(jRadioButton9);
        jRadioButton9.setText("허핑턴포스트");
        jRadioButton9.setActionCommand("HPTP");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton9);

        buttonGroup1.add(jRadioButton10);
        jRadioButton10.setText("다음");
        jRadioButton10.setActionCommand("DAUM");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton10);

        buttonGroup1.add(jRadioButton11);
        jRadioButton11.setText("네이버");
        jRadioButton11.setActionCommand("NAVER");
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton11);

        buttonGroup1.add(jRadioButton12);
        jRadioButton12.setText("연합뉴스");
        jRadioButton12.setActionCommand("YHN");
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton12);

        buttonGroup1.add(jRadioButton13);
        jRadioButton13.setText("노컷뉴스");
        jRadioButton13.setActionCommand("NCN");
        jRadioButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton13ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton13);

        buttonGroup1.add(jRadioButton14);
        jRadioButton14.setText("한국경제");
        jRadioButton14.setActionCommand("HKE");
        jRadioButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton14ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton14);

        buttonGroup1.add(jRadioButton15);
        jRadioButton15.setText("스타한국");
        jRadioButton15.setActionCommand("SHK");
        jRadioButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton15ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton15);

        buttonGroup1.add(jRadioButton16);
        jRadioButton16.setText("YTN");
        jRadioButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton16ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton16);

        buttonGroup1.add(jRadioButton17);
        jRadioButton17.setText("이데일리");
        jRadioButton17.setActionCommand("EDAILY");
        jRadioButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton17ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton17);

        buttonGroup1.add(jRadioButton18);
        jRadioButton18.setText("WIKITREE");
        jRadioButton18.setToolTipText("");
        jRadioButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton18ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton18);

        buttonGroup1.add(jRadioButton19);
        jRadioButton19.setText("JTBC");
        jRadioButton19.setToolTipText("");
        jRadioButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton19ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton19);

        buttonGroup1.add(jRadioButton20);
        jRadioButton20.setText("서울경제");
        jRadioButton20.setActionCommand("SEDAILY");
        jRadioButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton20ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton20);

        buttonGroup1.add(jRadioButton22);
        jRadioButton22.setText("이투데이");
        jRadioButton22.setToolTipText("");
        jRadioButton22.setActionCommand("ETODAY");
        jRadioButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton22ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton22);

        buttonGroup1.add(jRadioButton23);
        jRadioButton23.setText("NEWSIS");
        jRadioButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton23ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton23);

        buttonGroup1.add(jRadioButton24);
        jRadioButton24.setText("프레시안");
        jRadioButton24.setActionCommand("PRESSIAN");
        jRadioButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton24ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton24);

        buttonGroup1.add(jRadioButton25);
        jRadioButton25.setText("SBS");
        jRadioButton25.setToolTipText("");
        jRadioButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton25ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton25);

        buttonGroup1.add(jRadioButton26);
        jRadioButton26.setText("파이낸셜뉴스");
        jRadioButton26.setActionCommand("FNNEWS");
        jPanel3.add(jRadioButton26);

        buttonGroup1.add(jRadioButton27);
        jRadioButton27.setText("IMBC");
        jRadioButton27.setToolTipText("");
        jPanel3.add(jRadioButton27);

        jPanel7.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new java.awt.BorderLayout());

        urlLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        urlLbl.setText("주소 : ");
        urlLbl.setToolTipText("");
        jPanel4.add(urlLbl, java.awt.BorderLayout.WEST);
        jPanel4.add(textFieldPopupMenuPanel1, java.awt.BorderLayout.CENTER);

        executeBtn.setText("페이지 추출");
        executeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                executeBtnMouseClicked(evt);
            }
        });
        executeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeBtnActionPerformed(evt);
            }
        });
        jPanel9.add(executeBtn);

        extractImgBtn.setText("이미지추출");
        extractImgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extractImgBtnActionPerformed(evt);
            }
        });
        jPanel9.add(extractImgBtn);

        jButton2.setText("초기화");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton2);

        jPanel4.add(jPanel9, java.awt.BorderLayout.EAST);

        jPanel7.add(jPanel4, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel5.setLayout(new java.awt.GridLayout(1, 2));

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        newsTextArea.setColumns(20);
        newsTextArea.setRows(5);
        jScrollPane1.setViewportView(newsTextArea);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel6);

        jPanel1.add(jPanel5);

        jEditorPane1.setEditable(false);
        jScrollPane3.setViewportView(jEditorPane1);
        // add an html editor kit
        HTMLEditorKit kit = new HTMLEditorKit();
        jEditorPane1.setEditorKit(kit);

        // add some styles to the html
        StyleSheet styleSheet = kit.getStyleSheet();

        // create a document, set it on the jeditorpane, then add the html
        javax.swing.text.Document doc = kit.createDefaultDocument();
        jEditorPane1.setDocument(doc);
        //jEditorPane1.setText("blah blah blah");
        // create some simple html as a string
        String htmlString = "<html>\n"
        + "<body>\n"
        + "<h1>Welcome!</h1>\n"
        + "<h2>This is an H2 header</h2>\n"
        + "<p>This is some sample text</p>\n"
        + "<p><a href=\"http://devdaily.com/blog/\">devdaily blog</a></p>\n"
        + "</body>\n";
        //jEditorPane1.setText(htmlString);

        jPanel1.add(jScrollPane3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jButton1.setText("HTML View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton1);

        getContentPane().add(jPanel8, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void executeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_executeBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_executeBtnMouseClicked

    private void extractImgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extractImgBtnActionPerformed
        try {
            // TODO add your handling code here:
            url = textFieldPopupMenuPanel1.getTextField().getText();
            Document doc = Jsoup.connect(url).get();
            News gurl = new News();
            gurl.getURL(url);
            String protocol = gurl.getProtocol();
            String host = gurl.getHost();
            String path = gurl.getPath();

            JsoupChangeImageElementsAttribute.changeImageElementsAttribute(doc, protocol, host, path);

        } catch (IOException ex) {
            Logger.getLogger(NewsReader.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            System.out.println("이미지 추출 완료");
        }

    }//GEN-LAST:event_extractImgBtnActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        String newsCompany = getSelectedButtonText(buttonGroup1);
        textFieldPopupMenuPanel1.getTextField().setText("http://www.mt.co.kr");
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        String newsCompany = getSelectedButtonText(buttonGroup1);
        textFieldPopupMenuPanel1.getTextField().setText("http://www.sisain.com");
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        String newsCompany = getSelectedButtonText(buttonGroup1);
        textFieldPopupMenuPanel1.getTextField().setText("http://www.kmib.co.kr");
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        String newsCompany = getSelectedButtonText(buttonGroup1);
        textFieldPopupMenuPanel1.getTextField().setText("http://www.khan.co.kr/");
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
        String newsCompany = getSelectedButtonText(buttonGroup1);
        textFieldPopupMenuPanel1.getTextField().setText("http://www.hani.co.kr");
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
        String newsCompany = getSelectedButtonText(buttonGroup1);
        textFieldPopupMenuPanel1.getTextField().setText("http://joongang.joins.com");
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton21ActionPerformed
        // TODO add your handling code here:
        String newsCompany = getSelectedButtonText(buttonGroup1);
        textFieldPopupMenuPanel1.getTextField().setText("http://biz.chosun.com");
    }//GEN-LAST:event_jRadioButton21ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
        String newsCompany = getSelectedButtonText(buttonGroup1);
        textFieldPopupMenuPanel1.getTextField().setText("http://www.chosun.com");
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
        String newsCompany = getSelectedButtonText(buttonGroup1);
        textFieldPopupMenuPanel1.getTextField().setText("http://hankookilbo.com");
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        // TODO add your handling code here:
        String newsCompany = getSelectedButtonText(buttonGroup1);
        textFieldPopupMenuPanel1.getTextField().setText("http://www.huffingtonpost.kr");
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        // TODO add your handling code here:
        String newsCompany = getSelectedButtonText(buttonGroup1);
        textFieldPopupMenuPanel1.getTextField().setText("http://www.daum.net");
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
        // TODO add your handling code here:
        String newsCompany = getSelectedButtonText(buttonGroup1);
        textFieldPopupMenuPanel1.getTextField().setText("http://www.naver.com");
    }//GEN-LAST:event_jRadioButton11ActionPerformed

    private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
        // TODO add your handling code here:
        String newsCompany = getSelectedButtonText(buttonGroup1);
        textFieldPopupMenuPanel1.getTextField().setText("http://www.yonhapnews.co.kr");
    }//GEN-LAST:event_jRadioButton12ActionPerformed

    private void jRadioButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton13ActionPerformed
        // TODO add your handling code here:
        String newsCompany = getSelectedButtonText(buttonGroup1);
        textFieldPopupMenuPanel1.getTextField().setText("http://www.nocutnews.co.kr");
    }//GEN-LAST:event_jRadioButton13ActionPerformed

    private void jRadioButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton15ActionPerformed
        // TODO add your handling code here:
        String newsCompany = getSelectedButtonText(buttonGroup1);
        textFieldPopupMenuPanel1.getTextField().setText("http://star.hankookilbo.com");
    }//GEN-LAST:event_jRadioButton15ActionPerformed

    private void jRadioButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton16ActionPerformed
        // TODO add your handling code here:
        String newsCompany = getSelectedButtonText(buttonGroup1);
        textFieldPopupMenuPanel1.getTextField().setText("http://www.ytn.co.kr");
    }//GEN-LAST:event_jRadioButton16ActionPerformed

    private void jRadioButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton17ActionPerformed
        // TODO add your handling code here:
        String newsCompany = getSelectedButtonText(buttonGroup1);
        textFieldPopupMenuPanel1.getTextField().setText("http://www.edaily.co.kr");
    }//GEN-LAST:event_jRadioButton17ActionPerformed

    private void jRadioButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton18ActionPerformed
        // TODO add your handling code here:
        String newsCompany = getSelectedButtonText(buttonGroup1);
        textFieldPopupMenuPanel1.getTextField().setText("http://www.wikitree.co.kr");
    }//GEN-LAST:event_jRadioButton18ActionPerformed

    private void jRadioButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton20ActionPerformed
        // TODO add your handling code here:
        String newsCompany = getSelectedButtonText(buttonGroup1);
        textFieldPopupMenuPanel1.getTextField().setText("http://www.sedaily.com");
    }//GEN-LAST:event_jRadioButton20ActionPerformed

    private void jRadioButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton22ActionPerformed
        // TODO add your handling code here:
        String newsCompany = getSelectedButtonText(buttonGroup1);
        textFieldPopupMenuPanel1.getTextField().setText("http://www.etoday.co.kr");
    }//GEN-LAST:event_jRadioButton22ActionPerformed

    private void jRadioButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton23ActionPerformed
        // TODO add your handling code here:
        String newsCompany = getSelectedButtonText(buttonGroup1);
        textFieldPopupMenuPanel1.getTextField().setText("http://www.newsis.com");
    }//GEN-LAST:event_jRadioButton23ActionPerformed

    private void jRadioButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton24ActionPerformed
        // TODO add your handling code here:
        String newsCompany = getSelectedButtonText(buttonGroup1);
        textFieldPopupMenuPanel1.getTextField().setText("http://www.pressian.com");
    }//GEN-LAST:event_jRadioButton24ActionPerformed

    private void jRadioButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton14ActionPerformed
        // TODO add your handling code here:
        String newsCompany = getSelectedButtonText(buttonGroup1);
        textFieldPopupMenuPanel1.getTextField().setText("http://www.hankyung.com");
    }//GEN-LAST:event_jRadioButton14ActionPerformed

    private void jRadioButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton19ActionPerformed
        // TODO add your handling code here:
        String newsCompany = getSelectedButtonText(buttonGroup1);
        textFieldPopupMenuPanel1.getTextField().setText("http://jtbc.joins.com");
    }//GEN-LAST:event_jRadioButton19ActionPerformed

    private void jRadioButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton25ActionPerformed

    private void executeBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_executeBtnActionPerformed
        createHTMLFile();
    }// GEN-LAST:event_executeBtnActionPerformed

    public void createHTMLFile() {
        String newsCompany = getSelectedButtonText(buttonGroup1);
        System.out.println("newsCompany:" + newsCompany);
        if (newsCompany != null) {
            url = textFieldPopupMenuPanel1.getTextField().getText();
            if (!url.equals("")) {
                createHTMLFile(url, newsCompany);
            } else {
                JOptionPane.showMessageDialog(null, "저장할 주소를 입력하여 주세요.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "신문명을 선택하여 주세요.");
        }
    }

    private void createHTMLFile(String url, String newsCompany) {
        System.out.println("url:" + url);
        for (NewsPublisher np : NewsPublisher.values()) {
            String newsPublisherDomain = np.getName();
            System.out.println("newsPublisherDomain:" + newsPublisherDomain);
            if (url.startsWith(newsPublisherDomain)) {
                System.out.println("주소가 일치합니다.");
            }
        }
        StringBuilder sb = new StringBuilder();
        if (newsCompany.equals("MT")) {
            sb = NewsMoneyToday.createHTMLFile(url);
        } else if (newsCompany.equals("SSI")) {
            sb = NewsSisain.createHTMLFile(url);
        } else if (newsCompany.equals("KMIB")) {
            sb = NewsKmib.createHTMLFile(url);
        } else if (newsCompany.equals("KHSM")) {
        } else if (newsCompany.equals("HKR")) {
            sb = NewsHankyoreh.createHTMLFile(url);
        } else if (newsCompany.equals("JAIB")) {
            sb = NewsJoinsCom.createHTMLFile(url);
        } else if (newsCompany.equals("CHOSUNBIZ")) {
            sb = NewsBizChosunCom.createHTMLFile(url);
        } else if (newsCompany.equals("CSIB")) {
            sb = NewsChosun.createHTMLFile(url);
        } else if (newsCompany.equals("HKIB")) {
            sb = NewsHankookilbo.createHTMLFile(url);
        } else if (newsCompany.equals("HPTP")) {
            sb = NewsHuffingtonpost1.createHTMLFile(url);
        } else if (newsCompany.equals("DAUM")) {
            sb = NewsDaumNet.createHTMLFile(url);
        } else if (newsCompany.equals("NAVER")) {
            sb = NewsNaverCom.createHTMLFile(url);
        } else if (newsCompany.equals("YHN")) {
            sb = NewsYonhap.createHTMLFile(url);
        } else if (newsCompany.equals("NCN")) {
            sb = NewsNocutNews.createHTMLFile(url);
        } else if (newsCompany.equals("HKE")) {
            sb = NewsHankyung.createHTMLFile(url);
        } else if (newsCompany.equals("SHK")) {
            sb = NewsStarHankook.createHTMLFile(url);
        } else if (newsCompany.equals("YTN")) {
            sb = NewsYTN.createHTMLFile(url);
        } else if (newsCompany.equals("EDAILY")) {
            sb = NewsEdaily.createHTMLFile(url);
        } else if (newsCompany.equals("WIKITREE")) {
            sb = NewsWikitree.createHTMLFile(url);
        } else if (newsCompany.equals("JTBC")) {
            sb = NewsJTBC.createHTMLFile(url);
        } else if (newsCompany.equals("SEDAILY")) {
            sb = NewsSedailyCom.createHTMLFile(url);
        } else if (newsCompany.equals("ETODAY")) {
            sb = NewsEtodayCoKr.createHTMLFile(url);
        } else if (newsCompany.equals("NEWSIS")) {
            sb = NewsNewsisCom.createHTMLFile(url);
        } else if (newsCompany.equals("PRESSIAN")) {
            sb = NewsPressian.createHTMLFile(url);
        } else if (newsCompany.equals("SBS")) {
            sb = NewsSbsCoKr.createHTMLFile(url);
        } else if (newsCompany.equals("FNNEWS")) {
            sb = NewsFnnews.createHTMLFile(url);
        }
        System.out.println(sb.toString());
        Document htmlDoc = Jsoup.parse(sb.toString());
        newsTextArea.setText(htmlDoc.html());

        htmlDoc.select("meta").remove();
        sb.delete(0, sb.length());
        sb.setLength(0);
        jEditorPane1.setText(htmlDoc.html());
    }

    public String getSelectedButtonText(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getActionCommand();
            }
        }
        return null;
    }

    private void urlTfActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_urlTfActionPerformed

    }// GEN-LAST:event_urlTfActionPerformed

    private void urlTfKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_urlTfKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            // SwingUtilities.getWindowAncestor(evt.getComponent()).dispose();
            createHTMLFile();
        }
    }// GEN-LAST:event_urlTfKeyReleased
/*
//	private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton2ActionPerformed
//		// TODO add your handling code here:
//	}// GEN-LAST:event_jRadioButton2ActionPerformed
//
//	private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton1ActionPerformed
//		// TODO add your handling code here:
//	}// GEN-LAST:event_jRadioButton1ActionPerformed
//
//	private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton3ActionPerformed
//		// TODO add your handling code here:
//	}// GEN-LAST:event_jRadioButton3ActionPerformed
//
//	private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton10ActionPerformed
//		// TODO add your handling code here:
//	}// GEN-LAST:event_jRadioButton10ActionPerformed
//
//	private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton11ActionPerformed
//		// TODO add your handling code here:
//	}// GEN-LAST:event_jRadioButton11ActionPerformed
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String html = newsTextArea.getText();
        jEditorPane1.setText(html);
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        textFieldPopupMenuPanel1.getTextField().setText("");
        newsTextArea.setText("");
        jEditorPane1.setText("");
    }// GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewsReader.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new NewsReader().setVisible(true);
            }
        });
    }

    private String url = "http://news.mt.co.kr/newsPrint.html?no=2017051716214167566";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton executeBtn;
    private javax.swing.JButton extractImgBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea newsTextArea;
    private html.parsing.stock.TextFieldPopupMenuPanel textFieldPopupMenuPanel1;
    private javax.swing.JLabel urlLbl;
    // End of variables declaration//GEN-END:variables
}
