package html.parsing.stock.news;

import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Enumeration;
import java.util.Locale;

import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import html.parsing.stock.util.FileUtil;
import html.parsing.stock.util.StockUtil;

/**
 *
 * @author banks
 */
public class NownewsSeoulCoKr extends javax.swing.JFrame {

	public final static String USER_HOME = System.getProperty("user.home");
	private static Logger logger = LoggerFactory.getLogger(NownewsSeoulCoKr.class);
	
	String strYear = new SimpleDateFormat("yyyy", Locale.KOREAN).format(new Date());
	int iYear = Integer.parseInt(strYear);

	// String strYMD = new SimpleDateFormat("yyyy년 M월 d일 E ",
	// Locale.KOREAN).format(new Date());
	static String strYMD = "";

	DecimalFormat df = new DecimalFormat("###.##");

	String titleIdOrClass = "";
	String subtitleIdOrClass = "";
	String dateIdOrClass = "";
	String writerIdOrClass = "";
	String contentIdOrClass = "";
	String copyrightIdOrClass = "";

	/**
	 * Creates new form NewJFrame1
	 */
	public NownewsSeoulCoKr() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		buttonGroup2 = new javax.swing.ButtonGroup();
		buttonGroup3 = new javax.swing.ButtonGroup();
		buttonGroup4 = new javax.swing.ButtonGroup();
		buttonGroup5 = new javax.swing.ButtonGroup();
		buttonGroup6 = new javax.swing.ButtonGroup();
		urlInputPnl = new javax.swing.JPanel();
		urlLbl = new javax.swing.JLabel();
		urlTf = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		westLblPnl = new javax.swing.JPanel();
		titlePnl = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jPanel10 = new javax.swing.JPanel();
		urlLbl1 = new javax.swing.JLabel();
		jPanel8 = new javax.swing.JPanel();
		jRadioButton1 = new javax.swing.JRadioButton();
		jRadioButton2 = new javax.swing.JRadioButton();
		jRadioButton3 = new javax.swing.JRadioButton();
		subtitlePnl = new javax.swing.JPanel();
		jPanel14 = new javax.swing.JPanel();
		jPanel34 = new javax.swing.JPanel();
		urlLbl7 = new javax.swing.JLabel();
		jPanel15 = new javax.swing.JPanel();
		jRadioButton13 = new javax.swing.JRadioButton();
		jRadioButton14 = new javax.swing.JRadioButton();
		jRadioButton4 = new javax.swing.JRadioButton();
		datePnl = new javax.swing.JPanel();
		jPanel16 = new javax.swing.JPanel();
		jPanel35 = new javax.swing.JPanel();
		urlLbl8 = new javax.swing.JLabel();
		jPanel17 = new javax.swing.JPanel();
		jRadioButton15 = new javax.swing.JRadioButton();
		jRadioButton16 = new javax.swing.JRadioButton();
		jRadioButton5 = new javax.swing.JRadioButton();
		writerPnl = new javax.swing.JPanel();
		jPanel18 = new javax.swing.JPanel();
		jPanel36 = new javax.swing.JPanel();
		urlLbl9 = new javax.swing.JLabel();
		jPanel19 = new javax.swing.JPanel();
		jRadioButton17 = new javax.swing.JRadioButton();
		jRadioButton18 = new javax.swing.JRadioButton();
		jRadioButton6 = new javax.swing.JRadioButton();
		contentPnl = new javax.swing.JPanel();
		jPanel20 = new javax.swing.JPanel();
		jPanel37 = new javax.swing.JPanel();
		urlLbl10 = new javax.swing.JLabel();
		jPanel21 = new javax.swing.JPanel();
		jRadioButton19 = new javax.swing.JRadioButton();
		jRadioButton20 = new javax.swing.JRadioButton();
		jRadioButton7 = new javax.swing.JRadioButton();
		copyrightPnl = new javax.swing.JPanel();
		jPanel22 = new javax.swing.JPanel();
		jPanel38 = new javax.swing.JPanel();
		urlLbl11 = new javax.swing.JLabel();
		jPanel23 = new javax.swing.JPanel();
		jRadioButton21 = new javax.swing.JRadioButton();
		jRadioButton22 = new javax.swing.JRadioButton();
		jRadioButton8 = new javax.swing.JRadioButton();
		centerInputPnl = new javax.swing.JPanel();
		titlePnl1 = new javax.swing.JPanel();
		titleIdTf = new javax.swing.JTextField();
		subtitlePnl1 = new javax.swing.JPanel();
		subtitleIdTf = new javax.swing.JTextField();
		datePnl1 = new javax.swing.JPanel();
		dateIdTf = new javax.swing.JTextField();
		writerPnl1 = new javax.swing.JPanel();
		writerIdTf = new javax.swing.JTextField();
		contentPnl1 = new javax.swing.JPanel();
		contentIdTf = new javax.swing.JTextField();
		copyrightPnl1 = new javax.swing.JPanel();
		copyrightIdTf = new javax.swing.JTextField();
		pageExtractBtnPnl = new javax.swing.JPanel();
		jPanel9 = new javax.swing.JPanel();
		executeBtn = new javax.swing.JButton();
		resultLabel = new javax.swing.JLabel();
		jPanel11 = new javax.swing.JPanel();
		jButton8 = new javax.swing.JButton();
		eastDelBtnPnl = new javax.swing.JPanel();
		jPanel1 = new javax.swing.JPanel();
		jButton2 = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		jButton3 = new javax.swing.JButton();
		jPanel4 = new javax.swing.JPanel();
		jButton4 = new javax.swing.JButton();
		jPanel5 = new javax.swing.JPanel();
		jButton5 = new javax.swing.JButton();
		jPanel6 = new javax.swing.JPanel();
		jButton6 = new javax.swing.JButton();
		jPanel7 = new javax.swing.JPanel();
		jButton7 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("웹페이지 추출");
		setAlwaysOnTop(true);
		setMinimumSize(new java.awt.Dimension(500, 54));
		setSize(new java.awt.Dimension(500, 100));

		urlInputPnl.setLayout(new java.awt.BorderLayout());

		urlLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		urlLbl.setText("주소 : ");
		urlLbl.setToolTipText("");
		urlInputPnl.add(urlLbl, java.awt.BorderLayout.WEST);

		urlTf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
		urlTf.setToolTipText("");
		urlTf.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				urlTfActionPerformed(evt);
			}
		});
		urlTf.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyReleased(java.awt.event.KeyEvent evt) {
				urlTfKeyReleased(evt);
			}
		});
		urlInputPnl.add(urlTf, java.awt.BorderLayout.CENTER);

		jButton1.setText("삭제");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		urlInputPnl.add(jButton1, java.awt.BorderLayout.EAST);

		getContentPane().add(urlInputPnl, java.awt.BorderLayout.NORTH);

		westLblPnl.setLayout(new java.awt.GridLayout(6, 1));

		titlePnl.setLayout(new java.awt.BorderLayout());

		jPanel2.setLayout(new java.awt.BorderLayout());

		jPanel10.setPreferredSize(new java.awt.Dimension(70, 25));

		urlLbl1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		urlLbl1.setText("title : ");
		urlLbl1.setToolTipText("");
		jPanel10.add(urlLbl1);

		jPanel2.add(jPanel10, java.awt.BorderLayout.WEST);

		jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

		buttonGroup1.add(jRadioButton1);
		jRadioButton1.setText("id");
		jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton1ActionPerformed(evt);
			}
		});
		jPanel8.add(jRadioButton1);

		buttonGroup1.add(jRadioButton2);
		jRadioButton2.setText("class");
		jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton2ActionPerformed(evt);
			}
		});
		jPanel8.add(jRadioButton2);

		buttonGroup1.add(jRadioButton3);
		jRadioButton3.setSelected(true);
		jRadioButton3.setText("tag");
		jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton3ActionPerformed(evt);
			}
		});
		jPanel8.add(jRadioButton3);

		jPanel2.add(jPanel8, java.awt.BorderLayout.CENTER);

		titlePnl.add(jPanel2, java.awt.BorderLayout.WEST);

		westLblPnl.add(titlePnl);

		subtitlePnl.setLayout(new java.awt.BorderLayout());

		jPanel14.setLayout(new java.awt.BorderLayout());

		jPanel34.setPreferredSize(new java.awt.Dimension(70, 25));

		urlLbl7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		urlLbl7.setText("subtitle : ");
		urlLbl7.setToolTipText("");
		jPanel34.add(urlLbl7);

		jPanel14.add(jPanel34, java.awt.BorderLayout.WEST);

		jPanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

		buttonGroup2.add(jRadioButton13);
		jRadioButton13.setText("id");
		jRadioButton13.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton13ActionPerformed(evt);
			}
		});
		jPanel15.add(jRadioButton13);

		buttonGroup2.add(jRadioButton14);
		jRadioButton14.setText("class");
		jRadioButton14.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton14ActionPerformed(evt);
			}
		});
		jPanel15.add(jRadioButton14);

		buttonGroup2.add(jRadioButton4);
		jRadioButton4.setSelected(true);
		jRadioButton4.setText("tag");
		jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton4ActionPerformed(evt);
			}
		});
		jPanel15.add(jRadioButton4);

		jPanel14.add(jPanel15, java.awt.BorderLayout.CENTER);

		subtitlePnl.add(jPanel14, java.awt.BorderLayout.WEST);

		westLblPnl.add(subtitlePnl);

		datePnl.setLayout(new java.awt.BorderLayout());

		jPanel16.setLayout(new java.awt.BorderLayout());

		jPanel35.setPreferredSize(new java.awt.Dimension(70, 25));

		urlLbl8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		urlLbl8.setText("date : ");
		urlLbl8.setToolTipText("");
		jPanel35.add(urlLbl8);

		jPanel16.add(jPanel35, java.awt.BorderLayout.WEST);

		jPanel17.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

		buttonGroup3.add(jRadioButton15);
		jRadioButton15.setText("id");
		jRadioButton15.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton15ActionPerformed(evt);
			}
		});
		jPanel17.add(jRadioButton15);

		buttonGroup3.add(jRadioButton16);
		jRadioButton16.setText("class");
		jRadioButton16.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton16ActionPerformed(evt);
			}
		});
		jPanel17.add(jRadioButton16);

		buttonGroup3.add(jRadioButton5);
		jRadioButton5.setSelected(true);
		jRadioButton5.setText("tag");
		jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton5ActionPerformed(evt);
			}
		});
		jPanel17.add(jRadioButton5);

		jPanel16.add(jPanel17, java.awt.BorderLayout.CENTER);

		datePnl.add(jPanel16, java.awt.BorderLayout.WEST);

		westLblPnl.add(datePnl);

		writerPnl.setLayout(new java.awt.BorderLayout());

		jPanel18.setLayout(new java.awt.BorderLayout());

		jPanel36.setPreferredSize(new java.awt.Dimension(70, 25));

		urlLbl9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		urlLbl9.setText("writer : ");
		urlLbl9.setToolTipText("");
		jPanel36.add(urlLbl9);

		jPanel18.add(jPanel36, java.awt.BorderLayout.WEST);

		jPanel19.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

		buttonGroup4.add(jRadioButton17);
		jRadioButton17.setText("id");
		jRadioButton17.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton17ActionPerformed(evt);
			}
		});
		jPanel19.add(jRadioButton17);

		buttonGroup4.add(jRadioButton18);
		jRadioButton18.setText("class");
		jRadioButton18.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton18ActionPerformed(evt);
			}
		});
		jPanel19.add(jRadioButton18);

		buttonGroup4.add(jRadioButton6);
		jRadioButton6.setSelected(true);
		jRadioButton6.setText("tag");
		jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton6ActionPerformed(evt);
			}
		});
		jPanel19.add(jRadioButton6);

		jPanel18.add(jPanel19, java.awt.BorderLayout.CENTER);

		writerPnl.add(jPanel18, java.awt.BorderLayout.WEST);

		westLblPnl.add(writerPnl);

		contentPnl.setLayout(new java.awt.BorderLayout());

		jPanel20.setLayout(new java.awt.BorderLayout());

		jPanel37.setPreferredSize(new java.awt.Dimension(70, 25));

		urlLbl10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		urlLbl10.setText("content : ");
		urlLbl10.setToolTipText("");
		jPanel37.add(urlLbl10);

		jPanel20.add(jPanel37, java.awt.BorderLayout.WEST);

		jPanel21.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

		buttonGroup5.add(jRadioButton19);
		jRadioButton19.setText("id");
		jRadioButton19.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton19ActionPerformed(evt);
			}
		});
		jPanel21.add(jRadioButton19);

		buttonGroup5.add(jRadioButton20);
		jRadioButton20.setText("class");
		jRadioButton20.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton20ActionPerformed(evt);
			}
		});
		jPanel21.add(jRadioButton20);

		buttonGroup5.add(jRadioButton7);
		jRadioButton7.setSelected(true);
		jRadioButton7.setText("tag");
		jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton7ActionPerformed(evt);
			}
		});
		jPanel21.add(jRadioButton7);

		jPanel20.add(jPanel21, java.awt.BorderLayout.CENTER);

		contentPnl.add(jPanel20, java.awt.BorderLayout.WEST);

		westLblPnl.add(contentPnl);

		copyrightPnl.setLayout(new java.awt.BorderLayout());

		jPanel22.setLayout(new java.awt.BorderLayout());

		urlLbl11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		urlLbl11.setText("copyright :");
		urlLbl11.setToolTipText("");
		jPanel38.add(urlLbl11);

		jPanel22.add(jPanel38, java.awt.BorderLayout.WEST);

		jPanel23.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

		buttonGroup6.add(jRadioButton21);
		jRadioButton21.setText("id");
		jRadioButton21.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton21ActionPerformed(evt);
			}
		});
		jPanel23.add(jRadioButton21);

		buttonGroup6.add(jRadioButton22);
		jRadioButton22.setText("class");
		jRadioButton22.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton22ActionPerformed(evt);
			}
		});
		jPanel23.add(jRadioButton22);

		buttonGroup6.add(jRadioButton8);
		jRadioButton8.setSelected(true);
		jRadioButton8.setText("tag");
		jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton8ActionPerformed(evt);
			}
		});
		jPanel23.add(jRadioButton8);

		jPanel22.add(jPanel23, java.awt.BorderLayout.CENTER);

		copyrightPnl.add(jPanel22, java.awt.BorderLayout.WEST);

		westLblPnl.add(copyrightPnl);

		getContentPane().add(westLblPnl, java.awt.BorderLayout.WEST);

		centerInputPnl.setLayout(new java.awt.GridLayout(6, 1));

		titlePnl1.setLayout(new java.awt.BorderLayout());

		titleIdTf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
		titleIdTf.setToolTipText("");
		titleIdTf.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				titleIdTfActionPerformed(evt);
			}
		});
		titleIdTf.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyReleased(java.awt.event.KeyEvent evt) {
				titleIdTfKeyReleased(evt);
			}
		});
		titlePnl1.add(titleIdTf, java.awt.BorderLayout.CENTER);

		centerInputPnl.add(titlePnl1);

		subtitlePnl1.setLayout(new java.awt.BorderLayout());

		subtitleIdTf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
		subtitleIdTf.setToolTipText("");
		subtitleIdTf.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				subtitleIdTfActionPerformed(evt);
			}
		});
		subtitleIdTf.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyReleased(java.awt.event.KeyEvent evt) {
				subtitleIdTfKeyReleased(evt);
			}
		});
		subtitlePnl1.add(subtitleIdTf, java.awt.BorderLayout.CENTER);

		centerInputPnl.add(subtitlePnl1);

		datePnl1.setLayout(new java.awt.BorderLayout());

		dateIdTf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
		dateIdTf.setToolTipText("");
		dateIdTf.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				dateIdTfActionPerformed(evt);
			}
		});
		dateIdTf.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyReleased(java.awt.event.KeyEvent evt) {
				dateIdTfKeyReleased(evt);
			}
		});
		datePnl1.add(dateIdTf, java.awt.BorderLayout.CENTER);

		centerInputPnl.add(datePnl1);

		writerPnl1.setLayout(new java.awt.BorderLayout());

		writerIdTf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
		writerIdTf.setToolTipText("");
		writerIdTf.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				writerIdTfActionPerformed(evt);
			}
		});
		writerIdTf.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyReleased(java.awt.event.KeyEvent evt) {
				writerIdTfKeyReleased(evt);
			}
		});
		writerPnl1.add(writerIdTf, java.awt.BorderLayout.CENTER);

		centerInputPnl.add(writerPnl1);

		contentPnl1.setLayout(new java.awt.BorderLayout());

		contentIdTf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
		contentIdTf.setToolTipText("");
		contentIdTf.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				contentIdTfActionPerformed(evt);
			}
		});
		contentIdTf.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyReleased(java.awt.event.KeyEvent evt) {
				contentIdTfKeyReleased(evt);
			}
		});
		contentPnl1.add(contentIdTf, java.awt.BorderLayout.CENTER);

		centerInputPnl.add(contentPnl1);

		copyrightPnl1.setLayout(new java.awt.BorderLayout());

		copyrightIdTf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
		copyrightIdTf.setToolTipText("");
		copyrightIdTf.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				copyrightIdTfActionPerformed(evt);
			}
		});
		copyrightIdTf.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyReleased(java.awt.event.KeyEvent evt) {
				copyrightIdTfKeyReleased(evt);
			}
		});
		copyrightPnl1.add(copyrightIdTf, java.awt.BorderLayout.CENTER);

		centerInputPnl.add(copyrightPnl1);

		getContentPane().add(centerInputPnl, java.awt.BorderLayout.CENTER);

		pageExtractBtnPnl.setLayout(new java.awt.BorderLayout());

		executeBtn.setText("페이지 추출");
		executeBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				executeBtnActionPerformed(evt);
			}
		});
		jPanel9.add(executeBtn);
		jPanel9.add(resultLabel);

		pageExtractBtnPnl.add(jPanel9, java.awt.BorderLayout.CENTER);

		jButton8.setText("전체 초기화");
		jButton8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton8ActionPerformed(evt);
			}
		});
		jPanel11.add(jButton8);

		pageExtractBtnPnl.add(jPanel11, java.awt.BorderLayout.EAST);

		getContentPane().add(pageExtractBtnPnl, java.awt.BorderLayout.SOUTH);

		eastDelBtnPnl.setLayout(new java.awt.GridLayout(6, 1));

		jButton2.setText("초기화");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		jPanel1.add(jButton2);

		eastDelBtnPnl.add(jPanel1);

		jButton3.setText("초기화");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});
		jPanel3.add(jButton3);

		eastDelBtnPnl.add(jPanel3);

		jButton4.setText("초기화");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});
		jPanel4.add(jButton4);

		eastDelBtnPnl.add(jPanel4);

		jButton5.setText("초기화");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});
		jPanel5.add(jButton5);

		eastDelBtnPnl.add(jPanel5);

		jButton6.setText("초기화");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});
		jPanel6.add(jButton6);

		eastDelBtnPnl.add(jPanel6);

		jButton7.setText("초기화");
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton7ActionPerformed(evt);
			}
		});
		jPanel7.add(jButton7);

		eastDelBtnPnl.add(jPanel7);

		getContentPane().add(eastDelBtnPnl, java.awt.BorderLayout.LINE_END);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		urlTf.setText("");
	}// GEN-LAST:event_jButton1ActionPerformed

	private void executeBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_executeBtnActionPerformed
		createHTMLFile("");
	}// GEN-LAST:event_executeBtnActionPerformed

	private void titleIdTfActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_titleIdTfActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_titleIdTfActionPerformed

	private void titleIdTfKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_titleIdTfKeyReleased
		// TODO add your handling code here:
	}// GEN-LAST:event_titleIdTfKeyReleased

	private void subtitleIdTfActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_subtitleIdTfActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_subtitleIdTfActionPerformed

	private void subtitleIdTfKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_subtitleIdTfKeyReleased
		// TODO add your handling code here:
	}// GEN-LAST:event_subtitleIdTfKeyReleased

	private void dateIdTfActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_dateIdTfActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_dateIdTfActionPerformed

	private void dateIdTfKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_dateIdTfKeyReleased
		// TODO add your handling code here:
	}// GEN-LAST:event_dateIdTfKeyReleased

	private void writerIdTfActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_writerIdTfActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_writerIdTfActionPerformed

	private void writerIdTfKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_writerIdTfKeyReleased
		// TODO add your handling code here:
	}// GEN-LAST:event_writerIdTfKeyReleased

	private void contentIdTfActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_contentIdTfActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_contentIdTfActionPerformed

	private void contentIdTfKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_contentIdTfKeyReleased
		// TODO add your handling code here:
	}// GEN-LAST:event_contentIdTfKeyReleased

	private void copyrightIdTfActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_copyrightIdTfActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_copyrightIdTfActionPerformed

	private void copyrightIdTfKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_copyrightIdTfKeyReleased
		// TODO add your handling code here:
	}// GEN-LAST:event_copyrightIdTfKeyReleased

	private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton1ActionPerformed
		// TODO add your handling code here:
		JRadioButton radioButton = (JRadioButton) evt.getSource();
		String selectedOption = radioButton.getText();
		titleIdOrClass = selectedOption;
		System.out.println(selectedOption);
	}// GEN-LAST:event_jRadioButton1ActionPerformed

	private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton2ActionPerformed
		// TODO add your handling code here:
		JRadioButton radioButton = (JRadioButton) evt.getSource();
		String selectedOption = radioButton.getText();
		titleIdOrClass = selectedOption;
		System.out.println(selectedOption);
	}// GEN-LAST:event_jRadioButton2ActionPerformed

	private void jRadioButton13ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton13ActionPerformed
		// TODO add your handling code here:
		JRadioButton radioButton = (JRadioButton) evt.getSource();
		String selectedOption = radioButton.getText();
		subtitleIdOrClass = selectedOption;
		System.out.println(selectedOption);
	}// GEN-LAST:event_jRadioButton13ActionPerformed

	private void jRadioButton14ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton14ActionPerformed
		// TODO add your handling code here:
		JRadioButton radioButton = (JRadioButton) evt.getSource();
		String selectedOption = radioButton.getText();
		subtitleIdOrClass = selectedOption;
		System.out.println(selectedOption);
	}// GEN-LAST:event_jRadioButton14ActionPerformed

	private void jRadioButton15ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton15ActionPerformed
		// TODO add your handling code here:
		JRadioButton radioButton = (JRadioButton) evt.getSource();
		String selectedOption = radioButton.getText();
		dateIdOrClass = selectedOption;
		System.out.println(selectedOption);
	}// GEN-LAST:event_jRadioButton15ActionPerformed

	private void jRadioButton16ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton16ActionPerformed
		// TODO add your handling code here:
		JRadioButton radioButton = (JRadioButton) evt.getSource();
		String selectedOption = radioButton.getText();
		dateIdOrClass = selectedOption;
		System.out.println(selectedOption);
	}// GEN-LAST:event_jRadioButton16ActionPerformed

	private void jRadioButton17ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton17ActionPerformed
		// TODO add your handling code here:
		JRadioButton radioButton = (JRadioButton) evt.getSource();
		String selectedOption = radioButton.getText();
		writerIdOrClass = selectedOption;
		System.out.println(selectedOption);
	}// GEN-LAST:event_jRadioButton17ActionPerformed

	private void jRadioButton18ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton18ActionPerformed
		// TODO add your handling code here:
		JRadioButton radioButton = (JRadioButton) evt.getSource();
		String selectedOption = radioButton.getText();
		writerIdOrClass = selectedOption;
		System.out.println(selectedOption);
	}// GEN-LAST:event_jRadioButton18ActionPerformed

	private void jRadioButton19ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton19ActionPerformed
		// TODO add your handling code here:
		JRadioButton radioButton = (JRadioButton) evt.getSource();
		String selectedOption = radioButton.getText();
		contentIdOrClass = selectedOption;
		System.out.println(selectedOption);
	}// GEN-LAST:event_jRadioButton19ActionPerformed

	private void jRadioButton20ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton20ActionPerformed
		// TODO add your handling code here:
		JRadioButton radioButton = (JRadioButton) evt.getSource();
		String selectedOption = radioButton.getText();
		contentIdOrClass = selectedOption;
		System.out.println(selectedOption);
	}// GEN-LAST:event_jRadioButton20ActionPerformed

	private void jRadioButton21ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton21ActionPerformed
		// TODO add your handling code here:
		JRadioButton radioButton = (JRadioButton) evt.getSource();
		String selectedOption = radioButton.getText();
		copyrightIdOrClass = selectedOption;
		System.out.println(selectedOption);
	}// GEN-LAST:event_jRadioButton21ActionPerformed

	private void jRadioButton22ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton22ActionPerformed
		// TODO add your handling code here:
		JRadioButton radioButton = (JRadioButton) evt.getSource();
		String selectedOption = radioButton.getText();
		copyrightIdOrClass = selectedOption;
		System.out.println(selectedOption);
	}// GEN-LAST:event_jRadioButton22ActionPerformed

	private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton3ActionPerformed
		// TODO add your handling code here:
		JRadioButton radioButton = (JRadioButton) evt.getSource();
		String selectedOption = radioButton.getText();
		titleIdOrClass = "";
		System.out.println(selectedOption);
	}// GEN-LAST:event_jRadioButton3ActionPerformed

	private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton4ActionPerformed
		// TODO add your handling code here:
		JRadioButton radioButton = (JRadioButton) evt.getSource();
		String selectedOption = radioButton.getText();
		subtitleIdOrClass = "";
		System.out.println(selectedOption);
	}// GEN-LAST:event_jRadioButton4ActionPerformed

	private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton5ActionPerformed
		// TODO add your handling code here:
		JRadioButton radioButton = (JRadioButton) evt.getSource();
		String selectedOption = radioButton.getText();
		dateIdOrClass = "";
		System.out.println(selectedOption);
	}// GEN-LAST:event_jRadioButton5ActionPerformed

	private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton6ActionPerformed
		// TODO add your handling code here:
		JRadioButton radioButton = (JRadioButton) evt.getSource();
		String selectedOption = radioButton.getText();
		writerIdOrClass = "";
		System.out.println(selectedOption);
	}// GEN-LAST:event_jRadioButton6ActionPerformed

	private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton7ActionPerformed
		// TODO add your handling code here:
		JRadioButton radioButton = (JRadioButton) evt.getSource();
		String selectedOption = radioButton.getText();
		contentIdOrClass = "";
		System.out.println(selectedOption);
	}// GEN-LAST:event_jRadioButton7ActionPerformed

	private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton8ActionPerformed
		// TODO add your handling code here:
		JRadioButton radioButton = (JRadioButton) evt.getSource();
		String selectedOption = radioButton.getText();
		copyrightIdOrClass = "";
		System.out.println(selectedOption);
	}// GEN-LAST:event_jRadioButton8ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		// TODO add your handling code here:
		titleIdTf.setText("");
	}// GEN-LAST:event_jButton2ActionPerformed

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
		// TODO add your handling code here:
		subtitleIdTf.setText("");
	}// GEN-LAST:event_jButton3ActionPerformed

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
		// TODO add your handling code here:
		dateIdTf.setText("");
	}// GEN-LAST:event_jButton4ActionPerformed

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ActionPerformed
		// TODO add your handling code here:
		writerIdTf.setText("");
	}// GEN-LAST:event_jButton5ActionPerformed

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton6ActionPerformed
		// TODO add your handling code here:
		contentIdTf.setText("");
	}// GEN-LAST:event_jButton6ActionPerformed

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton7ActionPerformed
		// TODO add your handling code here:
		copyrightIdTf.setText("");
	}// GEN-LAST:event_jButton7ActionPerformed

	private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton8ActionPerformed
		// TODO add your handling code here:
		titleIdTf.setText("");
		subtitleIdTf.setText("");
		dateIdTf.setText("");
		writerIdTf.setText("");
		contentIdTf.setText("");
		copyrightIdTf.setText("");
	}// GEN-LAST:event_jButton8ActionPerformed

	private void urlTfActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_urlTfActionPerformed

	}// GEN-LAST:event_urlTfActionPerformed

	private void urlTfKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_urlTfKeyReleased
		if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
			// SwingUtilities.getWindowAncestor(evt.getComponent()).dispose();
			createHTMLFile("");
		}
	}// GEN-LAST:event_urlTfKeyReleased

	public String getSelectedButtonText(ButtonGroup buttonGroup) {
		for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
			AbstractButton button = buttons.nextElement();

			if (button.isSelected()) {
				return button.getText();
			}
		}
		return null;
	}

	public StringBuilder createHTMLFile(String strUrl) {
		return createHTMLFile(strUrl, "");
	}

	public StringBuilder createHTMLFile(String strUrl, String strMyComment) {

		String url = urlTf.getText();
		if (url == null || url.equals("")) {
			return null;
		}

		// 정상 동작
		titleIdOrClass = getSelectedButtonText(buttonGroup1);
		subtitleIdOrClass = getSelectedButtonText(buttonGroup2);
		dateIdOrClass = getSelectedButtonText(buttonGroup3);
		writerIdOrClass = getSelectedButtonText(buttonGroup3);
		contentIdOrClass = getSelectedButtonText(buttonGroup3);
		copyrightIdOrClass = getSelectedButtonText(buttonGroup3);

		String titleIdOrClassName = "";
		String subtitleIdOrClassName = "";
		String dateIdOrClassName = "";
		String writerIdOrClassName = "";
		String contentIdOrClassName = "";
		String copyrightIdOrClassName = "";

		String titleId = titleIdTf.getText();
		String subtitleId = subtitleIdTf.getText();
		String dateId = dateIdTf.getText();
		String writerId = writerIdTf.getText();
		String contentId = contentIdTf.getText();
		String copyrightId = copyrightIdTf.getText();

		if (titleIdOrClass.equals("id")) {
			titleIdOrClassName = "#" + titleId;
		} else if (titleIdOrClass.equals("class")) {
			titleIdOrClassName = "." + titleId;
		} else {
			titleIdOrClassName = titleId;
		}

		if (subtitleIdOrClass.equals("id")) {
			subtitleIdOrClassName = "#" + subtitleId;
		} else if (subtitleIdOrClass.equals("class")) {
			subtitleIdOrClassName = "." + subtitleId;
		} else {
			subtitleIdOrClassName = subtitleId;
		}

		if (dateIdOrClass.equals("id")) {
			dateIdOrClassName = "#" + dateId;
		} else if (dateIdOrClass.equals("class")) {
			dateIdOrClassName = "." + dateId;
		} else {
			dateIdOrClassName = dateId;
		}

		if (writerIdOrClass.equals("id")) {
			writerIdOrClassName = "#" + writerId;
		} else if (writerIdOrClass.equals("class")) {
			writerIdOrClassName = "." + writerId;
		} else {
			writerIdOrClassName = writerId;
		}

		if (contentIdOrClass.equals("id")) {
			contentIdOrClassName = "#" + contentId;
		} else if (contentIdOrClass.equals("class")) {
			contentIdOrClassName = "." + contentId;
		} else {
			contentIdOrClassName = contentId;
		}

		if (copyrightIdOrClass.equals("id")) {
			copyrightIdOrClassName = "#" + copyrightId;
		} else if (copyrightIdOrClass.equals("class")) {
			copyrightIdOrClassName = "." + copyrightId;
		} else {
			copyrightIdOrClassName = copyrightId;
		}

		logger.debug(" titleIdOrClass :" + titleIdOrClass);
		logger.debug(" subtitleIdOrClass :" + subtitleIdOrClass);
		logger.debug(" dateIdOrClass :" + dateIdOrClass);
		logger.debug(" writerIdOrClass :" + writerIdOrClass);
		logger.debug(" contentIdOrClass :" + contentIdOrClass);
		logger.debug(" copyrightIdOrClass :" + copyrightIdOrClass);

		logger.debug(" titleId :" + titleId);
		logger.debug(" subtitleId :" + subtitleId);
		logger.debug(" dateId :" + dateId);
		logger.debug(" writerId :" + writerId);
		logger.debug(" contentId :" + contentId);
		logger.debug(" copyrightId :" + copyrightId);

		logger.debug(" titleIdOrClassName :" + titleIdOrClassName);
		logger.debug(" subtitleIdOrClassName :" + subtitleIdOrClassName);
		logger.debug(" dateIdOrClassName :" + dateIdOrClassName);
		logger.debug(" writerIdOrClassName :" + writerIdOrClassName);
		logger.debug(" contentIdOrClassName :" + contentIdOrClassName);
		logger.debug(" copyrightIdOrClassName :" + copyrightIdOrClassName);

		News gurl = new News();
		gurl.getURL(url);
		String protocol = gurl.getProtocol();
		String host = gurl.getHost();
		String path = gurl.getPath();
		String protocolHost = gurl.getProtocolHost();

		StringBuilder sb1 = new StringBuilder();
		Document doc;
		String strTitleForFileName = "";
		String strFileNameDate = "";
		try {
			doc = Jsoup.connect(url).get();
			doc.select("iframe").remove();
			doc.select("script").remove();
			doc.select(".adsbygoogle").remove();
			// time 태그를 class명으로 가져오지 못해서 태그명을 변경한다.
			doc.select("time").tagName("div");
//			JsoupChangeAhrefElementsAttribute.changeAhrefElementsAttribute(doc, protocol, host, path);
//			JsoupChangeImageElementsAttribute.changeImageElementsAttribute(doc, protocol, host, path);
//			JsoupChangeLinkHrefElementsAttribute.changeLinkHrefElementsAttribute(doc, protocol, host, path);
//			JsoupChangeScriptSrcElementsAttribute.changeScriptSrcElementsAttribute(doc, protocol, host, path);

			String strTitle = "";
			String strSubtitle = "";
			String strDate = "";
			String strWriter = "";
			String strContent = "";
			String strCopyright = "";

			if (!titleId.equals("")) {
				strTitle = doc.select(titleIdOrClassName).get(0).text();
			}
			if (!subtitleId.equals("")) {
				strSubtitle = doc.select(subtitleIdOrClassName).html();
			}
			if (!dateId.equals("")) {
				strDate = doc.select(dateIdOrClassName).html();
				logger.debug("strDate:" + strDate);
				strDate = StockUtil.getDateForFileName(strDate);
				strFileNameDate = strDate;
			}
			if (!writerId.equals("")) {
				strWriter = doc.select(writerIdOrClassName).html();
			}
			if (!contentId.equals("")) {
				strContent = doc.select(contentIdOrClassName).html();
			}
			if (!copyrightId.equals("")) {
				strCopyright = doc.select(copyrightIdOrClassName).html();
			}

			strTitleForFileName = strTitle;
			strTitleForFileName = strTitleForFileName.replace("\"", "'");
			strTitleForFileName = strTitleForFileName.replace("“", "'");
			strTitleForFileName = strTitleForFileName.replace("”", "'");
			System.out.println("strTitleForFileName:" + strTitleForFileName);
//			String strEncoded = URLEncoder.encode(strTitleForFileName,"UTF8");
//			System.out.println("strEncoded:" + strEncoded);
//			strEncoded = strEncoded.replace("%E2%80%9C", "'");
//			strEncoded = strEncoded.replace("%E2%80%9D", "'");
//			System.out.println("s11:[" + strEncoded + "]");
//			strTitleForFileName = URLDecoder.decode(strEncoded, "UTF8");

			strContent = StockUtil.makeStockLinkStringByTxtFile(StockUtil.getMyCommentBox(strMyComment) + strContent);
			

			sb1.append("<!DOCTYPE html>\r\n");
			sb1.append("<html lang='ko'>\r\n");
			sb1.append("<head>\r\n");
			// sb1.append("<meta http-equiv=\"Content-Type\"
			// content=\"text/html;charset=utf-8\">\r\n");
			sb1.append("</head>\r\n");
			sb1.append("<body>\r\n");

			sb1.append(StockUtil.getMyCommentBox(strMyComment));

			sb1.append("<div style='width:741px'>\r\n");

			sb1.append("<h2 id='title'>[").append(strDate).append("] ").append(strTitle).append("</h2>\n");
			sb1.append("<h3>" + strSubtitle + "</h3>\r\n");
			sb1.append("<div>" + strDate + "</div>\r\n");
			sb1.append("<div>" + strWriter + "</div>\r\n");
			sb1.append("<div>" + strContent + "</div>\r\n");
			sb1.append("<div>" + strCopyright + "</div>\r\n");

			sb1.append("</div>\r\n");
			sb1.append("</body>\r\n");
			sb1.append("</html>\r\n");
			System.out.println("sb.toString:" + sb1.toString());

			File dir = new File(USER_HOME + File.separator + "documents" + File.separator + host);
			if (!dir.exists()) {
				dir.mkdirs();
			}

			String fileName = USER_HOME + File.separator + "documents" + File.separator + strFileNameDate + "_"
					+ strTitleForFileName + ".html";
			FileUtil.fileWrite(fileName, sb1.toString());

			fileName = USER_HOME + File.separator + "documents" + File.separator + strFileNameDate + "_"
					+ strTitleForFileName + ".html";
			FileUtil.fileWrite(fileName, sb1.toString());

		} catch (IOException e) {
		} finally {
			System.out.println("추출완료");
			resultLabel.setText("추출완료");
			System.out.println("파일 저장 완료");
		}
		return sb1;
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException
				| javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(NewsHankookilbo2.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new NownewsSeoulCoKr().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.ButtonGroup buttonGroup2;
	private javax.swing.ButtonGroup buttonGroup3;
	private javax.swing.ButtonGroup buttonGroup4;
	private javax.swing.ButtonGroup buttonGroup5;
	private javax.swing.ButtonGroup buttonGroup6;
	private javax.swing.JPanel centerInputPnl;
	private javax.swing.JTextField contentIdTf;
	private javax.swing.JPanel contentPnl;
	private javax.swing.JPanel contentPnl1;
	private javax.swing.JTextField copyrightIdTf;
	private javax.swing.JPanel copyrightPnl;
	private javax.swing.JPanel copyrightPnl1;
	private javax.swing.JTextField dateIdTf;
	private javax.swing.JPanel datePnl;
	private javax.swing.JPanel datePnl1;
	private javax.swing.JPanel eastDelBtnPnl;
	private javax.swing.JButton executeBtn;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel10;
	private javax.swing.JPanel jPanel11;
	private javax.swing.JPanel jPanel14;
	private javax.swing.JPanel jPanel15;
	private javax.swing.JPanel jPanel16;
	private javax.swing.JPanel jPanel17;
	private javax.swing.JPanel jPanel18;
	private javax.swing.JPanel jPanel19;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel20;
	private javax.swing.JPanel jPanel21;
	private javax.swing.JPanel jPanel22;
	private javax.swing.JPanel jPanel23;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel34;
	private javax.swing.JPanel jPanel35;
	private javax.swing.JPanel jPanel36;
	private javax.swing.JPanel jPanel37;
	private javax.swing.JPanel jPanel38;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPanel jPanel8;
	private javax.swing.JPanel jPanel9;
	private javax.swing.JRadioButton jRadioButton1;
	private javax.swing.JRadioButton jRadioButton13;
	private javax.swing.JRadioButton jRadioButton14;
	private javax.swing.JRadioButton jRadioButton15;
	private javax.swing.JRadioButton jRadioButton16;
	private javax.swing.JRadioButton jRadioButton17;
	private javax.swing.JRadioButton jRadioButton18;
	private javax.swing.JRadioButton jRadioButton19;
	private javax.swing.JRadioButton jRadioButton2;
	private javax.swing.JRadioButton jRadioButton20;
	private javax.swing.JRadioButton jRadioButton21;
	private javax.swing.JRadioButton jRadioButton22;
	private javax.swing.JRadioButton jRadioButton3;
	private javax.swing.JRadioButton jRadioButton4;
	private javax.swing.JRadioButton jRadioButton5;
	private javax.swing.JRadioButton jRadioButton6;
	private javax.swing.JRadioButton jRadioButton7;
	private javax.swing.JRadioButton jRadioButton8;
	private javax.swing.JPanel pageExtractBtnPnl;
	private javax.swing.JLabel resultLabel;
	private javax.swing.JTextField subtitleIdTf;
	private javax.swing.JPanel subtitlePnl;
	private javax.swing.JPanel subtitlePnl1;
	private javax.swing.JTextField titleIdTf;
	private javax.swing.JPanel titlePnl;
	private javax.swing.JPanel titlePnl1;
	private javax.swing.JPanel urlInputPnl;
	private javax.swing.JLabel urlLbl;
	private javax.swing.JLabel urlLbl1;
	private javax.swing.JLabel urlLbl10;
	private javax.swing.JLabel urlLbl11;
	private javax.swing.JLabel urlLbl7;
	private javax.swing.JLabel urlLbl8;
	private javax.swing.JLabel urlLbl9;
	private javax.swing.JTextField urlTf;
	private javax.swing.JPanel westLblPnl;
	private javax.swing.JTextField writerIdTf;
	private javax.swing.JPanel writerPnl;
	private javax.swing.JPanel writerPnl1;
	// End of variables declaration//GEN-END:variables
}
