/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.coupang.partners;

import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.net.URI;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;
import org.slf4j.LoggerFactory;

import html.parsing.stock.util.FileUtil;

/**
 *
 * @author banks
 */
public class CoupangPartnersCreateLink2 extends javax.swing.JFrame {

	private static org.slf4j.Logger logger = LoggerFactory.getLogger(CoupangPartnersCreateLink2.class);
	final static String userHome = System.getProperty("user.home");
	URI uri = null;
	String fileName="";

	/**
	 * Creates new form NewJFrame1
	 */
	public CoupangPartnersCreateLink2() {
		initComponents();
		initList();
	}

	void initList() {
	}

	private static void open(URI uri) {
		if (Desktop.isDesktopSupported()) {
			try {
				Desktop.getDesktop().browse(uri);
			} catch (IOException e) {
				/* TODO: error handling */ }
		} else {
			/* TODO: error handling */ }
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                buttonGroup1 = new javax.swing.ButtonGroup();
                jPanel0 = new javax.swing.JPanel();
                jPanel5 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jPanel1 = new javax.swing.JPanel();
                jTabbedPane1 = new javax.swing.JTabbedPane();
                jSplitPane1 = new javax.swing.JSplitPane();
                jScrollPane1 = new javax.swing.JScrollPane();
                newsTextArea = new javax.swing.JTextArea();
                jSplitPane2 = new javax.swing.JSplitPane();
                jPanel2 = new javax.swing.JPanel();
                jButton1 = new javax.swing.JButton();
                jScrollPane4 = new javax.swing.JScrollPane();
                newsTextArea1 = new javax.swing.JTextArea();
                jPanel3 = new javax.swing.JPanel();
                jPanel4 = new javax.swing.JPanel();
                jButton3 = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("웹페이지 추출");
                setMinimumSize(new java.awt.Dimension(800, 500));
                setSize(new java.awt.Dimension(1000, 600));

                jPanel0.setMinimumSize(new java.awt.Dimension(60, 50));
                jPanel0.setName(""); // NOI18N
                jPanel0.setLayout(new java.awt.GridLayout());

                jPanel5.setLayout(new java.awt.GridLayout());

                jLabel1.setFont(new java.awt.Font("굴림", 0, 14)); // NOI18N
                jLabel1.setText("쿠팡 파트너스 상품 추출");
                jPanel5.add(jLabel1);

                jPanel0.add(jPanel5);

                getContentPane().add(jPanel0, java.awt.BorderLayout.PAGE_START);

                jPanel1.setLayout(new java.awt.GridLayout(1, 2));

                jSplitPane1.setDividerLocation(350);

                jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 106));

                newsTextArea.setColumns(50);
                newsTextArea.setRows(5);
                newsTextArea.setMinimumSize(new java.awt.Dimension(200, 300));
                newsTextArea.setPreferredSize(new java.awt.Dimension(454, 204));
                jScrollPane1.setViewportView(newsTextArea);

                jSplitPane1.setLeftComponent(jScrollPane1);

                jSplitPane2.setDividerLocation(150);

                jButton1.setText("Create Coupang Link =>");
                jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jButton1MouseClicked(evt);
                        }
                });
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(201, 201, 201)
                                .addComponent(jButton1)
                                .addContainerGap(167, Short.MAX_VALUE))
                );

                jSplitPane2.setLeftComponent(jPanel2);

                jScrollPane4.setPreferredSize(new java.awt.Dimension(200, 106));

                newsTextArea1.setColumns(20);
                newsTextArea1.setRows(5);
                jScrollPane4.setViewportView(newsTextArea1);

                jSplitPane2.setRightComponent(jScrollPane4);

                jSplitPane1.setRightComponent(jSplitPane2);

                jTabbedPane1.addTab("소스입력", jSplitPane1);

                jPanel1.add(jTabbedPane1);

                getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

                jPanel3.setLayout(new java.awt.GridLayout());

                jButton3.setText("저장");
                jButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton3ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(373, 373, 373)
                                .addComponent(jButton3)
                                .addContainerGap(434, Short.MAX_VALUE))
                );
                jPanel4Layout.setVerticalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                );

                jPanel3.add(jPanel4);

                getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
	    FileWriter fw = null;
	    String htmlSource = newsTextArea.getText();
	    Document doc = Jsoup.parse(htmlSource);
	    doc.select("button").remove();

	    SimpleDateFormat sdf0 = new SimpleDateFormat("[yyyy-MM-dd]", Locale.KOREAN);
	    String strYMD = sdf0.format(new Date());

	    Elements h1Els = doc.select("h1");
	    logger.debug("h1Els.size:" + h1Els.size());
	    for (Element h1El : h1Els) {
		    String styleClass = h1El.attr("class");
		    styleClass = styleClass.replace("-", "_");
		    h1El.attr("class", styleClass);
	    }
	    String strTitle = doc.select("h1 .mr1em").text();
	    logger.debug("strTitle:" + strTitle);

	    Elements divEls = doc.select("div");
	    for (Element divEl : divEls) {
		    String styleClass = divEl.attr("class");
		    styleClass = styleClass.replace("-", "_");
		    divEl.attr("class", styleClass);
	    }

	    Elements spanEls = doc.select("span");
	    for (Element spanEl : spanEls) {
		    String styleClass = spanEl.attr("class");
		    styleClass = styleClass.replace("-", "_");
		    spanEl.attr("class", styleClass);
	    }
	    doc.select(".delivery_badge").remove();

	    StringBuffer sb1 = new StringBuffer();
	    Element e1 = doc.select(".product_list").get(0);
	    //<a href="https://coupa.ng/bDgoXJ" target="_blank"><img src="https://static.coupangcdn.com/image/affiliate/banner/226ebd857435cd57616247dd0c3d2b46@2x.jpg" alt="트리트룸 시그니처 샴푸 화이트머스크향, 1077ml, 2개" width="120" height="240"></a>
	    sb1.append("<html>\r\n");
	    sb1.append("<body>\r\n");
	    sb1.append("<h1>").append(strYMD).append(" ").append(strTitle).append("</h1>\r\n");
	    sb1.append("<div style='display:inline-block'>\r\n");
	    sb1.append("<ul style='list-style:none;padding-left:0;'>\r\n");
	    Elements rowEls = e1.select(".product_row");
	    for (int i = 0; i < rowEls.size(); i++) {
		    Element rowEl = rowEls.get(i);

		    Elements itemEls = rowEl.select(".product_item");
		    for (int j = 0; j < itemEls.size(); j++) {
			    Element itemEl = itemEls.get(j);
			    if (itemEl.text().equals("")) {
				    continue;
			    }
			    logger.debug("itemEl:" + itemEl);
			    String strImg = itemEl.select("img").outerHtml();
			    String strProdName = itemEl.select(".product_meta .product_description .LinesEllipsis").text();
			    Elements discountEls = itemEl.select(".product_meta .product_price .discount");
			    Element discountEl = null;
			    String strCoupangPrice = "";
			    String strDiscountRate = "";
			    if (discountEls.size() > 0) {
				    discountEl = itemEl.select(".product_meta .product_price .discount").get(0);
				    logger.debug("discountEl:" + discountEl);
				    Element coupangPriceEl = discountEl.select("span").get(0);
				    logger.debug("coupangPriceEl:" + coupangPriceEl);
				    strCoupangPrice = coupangPriceEl.text();
				    discountEl.select("span").remove();
				    strDiscountRate = discountEl.text();
			    }
			    String strSalePrice = itemEl.select(".product_meta .product_price .sale_price").text();

			    sb1.append("<li style='height:320px;float:left;background-color: #fff; box-shadow: none; border: 1px solid #dfe1e5; border-radius: 8px; overflow: hidden; margin: 0 0 6px 0;margin-right:8px;margin-top:1px;'>\r\n");
			    sb1.append("<a href='CoupangShortenedURL' target='_blank' style='text-decoration:none'>\r\n");
			    sb1.append(strImg + "<br/>\r\n");
			    sb1.append("<div style='text-align:center;width:212px;font-size:12px;white-space: nowrap;overflow: hidden;text-overflow: ellipsis;'>" + strProdName + "</div>\r\n");
			    sb1.append("<div style='text-align:center;color:red;font-weight:bold;font-size:20px;'>" + strDiscountRate + "</div>\r\n");
			    sb1.append("<div style='text-align:center;color:#111;font-weight:bold;font-size:18px;text-decoration:line-through;'>" + strCoupangPrice + "</div>\r\n");
			    sb1.append("<div style='text-align:center;color:#ae0000;font-weight:bold;font-size:20px;'>" + strSalePrice + "</div>\r\n");
			    sb1.append("</a>\r\n");
			    sb1.append("</li>\r\n");
		    }
	    }
	    sb1.append("</ul>\r\n");
	    sb1.append("</div>\r\n");
	    sb1.append("<div><br/></div>\r\n");
	    sb1.append("<div>\r\n");
	    sb1.append("- 로켓와우 회원에 가입해야 일반 쿠팡가보다 저렴하게 구매할 수 있습니다.<br>\r\n");
	    sb1.append("- 로켓와우 회원은 월2900원을 결제해야되나 하나만 사더라도 무료배송 가능합니다.<br>\r\n");
	    sb1.append("- 특가 상품 하나만 잘 사면 로켓와우 회원 결제 비용이 아깝지 않습니다.<br><br>\r\n");
	    sb1.append("※ 파트너스 활동을 통해 일정액의 수수료를 제공받을 수 있음<br>\r\n");
	    sb1.append("</div>\r\n");
	    sb1.append("<br/><br/><br/>\r\n");
	    sb1.append("</body>\r\n");
	    sb1.append("</html>\r\n");
	    newsTextArea1.setText(sb1.toString());
	    SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd HH.mm.ss.SSS", Locale.KOREAN);
	    String strDate = sdf.format(new Date());
	    fileName = userHome + File.separator + "documents" + File.separator + strDate + "_coupang.partners.html";
//	    FileUtil.fileWrite(fileName, Jsoup.parse(sb1.toString()).html());
	    FileUtil.fileWrite(fileName, sb1.toString());
    }//GEN-LAST:event_jButton1MouseClicked

        private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                // TODO add your handling code here:
                String writeContent = newsTextArea1.getText();
		if(writeContent.equals("")) return;
                SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd HH.mm.ss.SSS", Locale.KOREAN);
                String strDate = sdf.format(new Date());
                fileName = userHome + File.separator + "documents" + File.separator + strDate + "_coupang.partners.html";
                //	    FileUtil.fileWrite(fileName, Jsoup.parse(sb1.toString()).html());
                FileUtil.fileWrite(fileName, writeContent);
        }//GEN-LAST:event_jButton3ActionPerformed

	private void urlTfActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_urlTfActionPerformed

	}// GEN-LAST:event_urlTfActionPerformed

	private void urlTfKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_urlTfKeyReleased
		if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
			// SwingUtilities.getWindowAncestor(evt.getComponent()).dispose();
		}
	}// GEN-LAST:event_urlTfKeyReleased
/*
//	private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton2ActionPerformed
//		// TODO add your handling code here:
//	}// GEN-LAST:event_jRadioButton2ActionPerformed
//
//	private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton1ActionPerformed
//		// TODO add your handling code here:
//	}// GEN-LAST:event_jRadioButton1ActionPerformed
//
//	private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton3ActionPerformed
//		// TODO add your handling code here:
//	}// GEN-LAST:event_jRadioButton3ActionPerformed
//
//	private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton10ActionPerformed
//		// TODO add your handling code here:
//	}// GEN-LAST:event_jRadioButton10ActionPerformed
//
//	private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton11ActionPerformed
//		// TODO add your handling code here:
//	}// GEN-LAST:event_jRadioButton11ActionPerformed
	 */
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		String html = newsTextArea.getText();
	}// GEN-LAST:event_jButton1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(CoupangPartnersCreateLink2.class.getName()).log(java.util.logging.Level.SEVERE, null,
				ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new CoupangPartnersCreateLink2().setVisible(true);
			}
		});
	}

	private String url = "http://news.mt.co.kr/newsPrint.html?no=2017051716214167566";
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.ButtonGroup buttonGroup1;
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton3;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JPanel jPanel0;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane4;
        private javax.swing.JSplitPane jSplitPane1;
        private javax.swing.JSplitPane jSplitPane2;
        private javax.swing.JTabbedPane jTabbedPane1;
        private javax.swing.JTextArea newsTextArea;
        private javax.swing.JTextArea newsTextArea1;
        // End of variables declaration//GEN-END:variables
}
