package html.parsing.stock.focus;

import html.parsing.stock.model.StockVO;
import html.parsing.stock.util.DataSort;
import html.parsing.stock.util.FileUtil;
import html.parsing.stock.util.GlobalVariables;
import html.parsing.stock.util.NaverUtil;
import html.parsing.stock.util.StockUtil;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;
import org.apache.commons.lang3.StringUtils;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * 유튜브에서 네이버로 공유할때 공유하기 화면
 */
public class StockWeeks52NewLowHighPriceTodayOneFileJFrameV2 extends javax.swing.JFrame implements Runnable {

	final static String USER_HOME = System.getProperty("user.home");
	private Logger logger = LoggerFactory.getLogger(StockWeeks52NewLowHighPriceTodayOneFileJFrameV2.class);

	String strYear = new SimpleDateFormat("yyyy", Locale.KOREAN).format(new Date());
	int iYear = Integer.parseInt(strYear);

	DecimalFormat df = new DecimalFormat("###.##");

	String strHms = new SimpleDateFormat("HHmmss", Locale.KOREAN).format(new Date());
	int iHms = Integer.parseInt(strHms);

	SimpleDateFormat sdf = new SimpleDateFormat("yyyy.MM.dd", Locale.KOREAN);
	String strDefaultDate = sdf.format(new Date());
	// String strYyyyMmDd = new SimpleDateFormat("yyyy년 M월 d일
	// E",Locale.KOREAN).format(new Date());
	int iYmd = Integer.parseInt(strDefaultDate.replaceAll("\\.", ""));
	String strYmdDash = strDefaultDate.replaceAll("\\.", "-");
	String strYmdDashBracket = "[" + strDefaultDate.replaceAll("\\.", "-") + "]";

	String kospiFileName = GlobalVariables.kospiFileName;
	String kosdaqFileName = GlobalVariables.kosdaqFileName;
	String strStockCode = "011170";
	String strStockName = "롯데케미칼";

	List<StockVO> kospiStockList = new ArrayList<StockVO>();
	List<StockVO> kosdaqStockList = new ArrayList<StockVO>();

	List<StockVO> kospiStockDataList = new ArrayList<StockVO>();
	List<StockVO> kosdaqStockDataList = new ArrayList<StockVO>();

	LinkedHashMap<String, List<StockVO>> newLowHighPriceMap = new LinkedHashMap<String, List<StockVO>>();
	List<StockVO> newLowPriceList = new ArrayList<StockVO>();
	List<StockVO> newHighPriceList = new ArrayList<StockVO>();
	List<StockVO> kospiNewLowPriceList = new ArrayList<StockVO>();
	List<StockVO> kospiNewHighPriceList = new ArrayList<StockVO>();
	List<StockVO> kosdaqNewLowPriceList = new ArrayList<StockVO>();
	List<StockVO> kosdaqNewHighPriceList = new ArrayList<StockVO>();
	String strFileName;

	String strBlogId = "";
	String strNidAut = "";
	String strNidSes = "";

	/**
	 * Creates new form StockMarketPriceRunJFrame
	 */
	public StockWeeks52NewLowHighPriceTodayOneFileJFrameV2() {
		initComponents();
//		execute();
	}

	public void execute() {
		strNidAut = nidAutTa.getText();
		strNidSes = nidSesTa.getText();
//		NaverUtil.naverBlogLinkShare(strNidAut, strNidSes, strShareUrl, strShareTitle, strCategoryName, contentSb, rootPane);
		if (strNidAut.equals("")) {
			JOptionPane.showMessageDialog(rootPane, "NID_AUT를 입력하여 주세요.", "Warning", JOptionPane.WARNING_MESSAGE);
			return;
		} else if (strNidSes.equals("")) {
			JOptionPane.showMessageDialog(rootPane, "NID_SES를 입력하여 주세요.", "Warning", JOptionPane.WARNING_MESSAGE);
			return;
		}

		start();
	}

	public void start() {
		Runnable r = new StockWeeks52NewLowHighPriceTodayOneFileJFrameV2(strNidAut, strNidSes);
		Thread t = new Thread(r);
		t.start();
	}

	public StockWeeks52NewLowHighPriceTodayOneFileJFrameV2(String strNidAut, String strNidSes) {
		logger = LoggerFactory.getLogger(getClass());
		this.strNidAut = strNidAut;
		this.strNidSes = strNidSes;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		jPanel6 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		nidAutTa = new javax.swing.JTextArea();
		jPanel7 = new javax.swing.JPanel();
		jButton5 = new javax.swing.JButton();
		jPanel5 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		nidSesTa = new javax.swing.JTextArea();
		jPanel4 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("네이버 블로그 공유");
		setPreferredSize(new java.awt.Dimension(800, 400));

		jPanel1.setLayout(new java.awt.GridLayout(2, 0));

		jLabel3.setText("주식 시세 조회,저장, 블로그에 글쓰기");
		jPanel1.add(jLabel3);

		getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

		jPanel6.setPreferredSize(new java.awt.Dimension(1215, 160));

		jPanel2.setPreferredSize(new java.awt.Dimension(600, 33));
		jPanel2.setLayout(new java.awt.BorderLayout());

		jLabel1.setText("NID_AUT");
		jLabel1.setPreferredSize(new java.awt.Dimension(70, 15));
		jPanel2.add(jLabel1, java.awt.BorderLayout.WEST);

		jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 106));

		nidAutTa.setColumns(25);
		nidAutTa.setLineWrap(true);
		nidAutTa.setRows(1);
		jScrollPane1.setViewportView(nidAutTa);

		jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

		jButton5.setText("삭제");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});
		jPanel7.add(jButton5);

		jPanel2.add(jPanel7, java.awt.BorderLayout.EAST);

		jPanel6.add(jPanel2);

		jPanel5.setPreferredSize(new java.awt.Dimension(600, 200));
		jPanel5.setLayout(new java.awt.BorderLayout());

		jLabel2.setText("NID_SES");
		jLabel2.setPreferredSize(new java.awt.Dimension(70, 15));
		jPanel5.add(jLabel2, java.awt.BorderLayout.WEST);

		jScrollPane2.setPreferredSize(new java.awt.Dimension(500, 250));

		nidSesTa.setColumns(25);
		nidSesTa.setLineWrap(true);
		nidSesTa.setRows(10);
		jScrollPane2.setViewportView(nidSesTa);

		jPanel5.add(jScrollPane2, java.awt.BorderLayout.CENTER);

		jButton1.setText("삭제");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jPanel4.add(jButton1);

		jPanel5.add(jPanel4, java.awt.BorderLayout.EAST);

		jPanel6.add(jPanel5);

		getContentPane().add(jPanel6, java.awt.BorderLayout.CENTER);

		jButton2.setText("네이버 블로그에 업로드");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		jPanel3.add(jButton2);

		getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

		getAccessibleContext().setAccessibleName("주식 시세 조회");

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		// TODO add your handling code here:
		execute();
	}// GEN-LAST:event_jButton2ActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		nidSesTa.setText("");
	}// GEN-LAST:event_jButton1ActionPerformed

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ActionPerformed
		// TODO add your handling code here:
		nidAutTa.setText("");
	}// GEN-LAST:event_jButton5ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(StockWeeks52NewLowHighPriceTodayOneFileJFrameV2.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(StockWeeks52NewLowHighPriceTodayOneFileJFrameV2.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(StockWeeks52NewLowHighPriceTodayOneFileJFrameV2.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(StockWeeks52NewLowHighPriceTodayOneFileJFrameV2.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new StockWeeks52NewLowHighPriceTodayOneFileJFrameV2().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton5;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTextArea nidAutTa;
	private javax.swing.JTextArea nidSesTa;
	// End of variables declaration//GEN-END:variables

	@Override
	public void run() {
		System.out.println("run...............");
		kospiStockList = StockUtil.readStockCodeNameList("코스피");
		if (kospiStockList != null) {
			logger.debug("kospiStockList.size1 :" + kospiStockList.size());
		} else {
			logger.debug("kospiStockList is null");
		}
		kosdaqStockList = StockUtil.readStockCodeNameList("코스닥");
		if (kosdaqStockList != null) {
			logger.debug("kosdaqStockList.size1 :" + kosdaqStockList.size());
		} else {
			logger.debug("kosdaqStockList is null");
		}

		/**
		 * 날짜 정보 가져오기
		 */
		StockVO svo4Date = kospiStockList.get(0);
		strYmdDashBracket = StockUtil.getDateInfo(svo4Date.getStockCode());

		for (int i = 0; i < kospiStockList.size(); i++) {
			StockVO svo = kospiStockList.get(i);
			logger.debug("======================================================================");
			logger.debug("코스피." + (i + 1) + "." + svo.getStockCode() + "." + svo.getStockName());
			logger.debug("======================================================================");
			getStockInfo((i + 1), svo.getStockCode(), svo.getStockName(), "P");
		}
		/*
		 * Collections.sort(kospiStockDataList, new NameAscCompare());
		 * writeFile(kospiStockDataList, "코스피", "이름순");
		 * 
		 * Collections.sort(kospiStockDataList, new
		 * Weeks52NewHighPriceVsCurPriceDownRatioAscCompare());
		 * writeFile(kospiStockDataList, "코스피", "하락율순");
		 * 
		 * Collections.sort(kospiStockDataList, new
		 * Weeks52NewLowPriceVsCurPriceUpRatioDescCompare());
		 * writeFile(kospiStockDataList, "코스피", "상승율순");
		 */
		logger.debug("kosdaqStockList.size :" + kosdaqStockList.size());
		for (int i = 0; i < kosdaqStockList.size(); i++) {
			StockVO svo = kosdaqStockList.get(i);
			logger.debug("======================================================================");
			logger.debug("코스닥." + (i + 1) + "." + svo.getStockCode() + "." + svo.getStockName());
			logger.debug("======================================================================");
			getStockInfo((i + 1), svo.getStockCode(), svo.getStockName(), "D");
		}
		/*
		 * Collections.sort(kosdaqStockDataList, new NameAscCompare());
		 * writeFile(kosdaqStockDataList, "코스닥", "이름순");
		 * 
		 * Collections.sort(kosdaqStockDataList, new
		 * Weeks52NewHighPriceVsCurPriceDownRatioDescCompare());
		 * writeFile(kosdaqStockDataList, "코스닥", "하락율순");
		 * 
		 * Collections.sort(kosdaqStockDataList, new
		 * Weeks52NewLowPriceVsCurPriceUpRatioDescCompare());
		 * writeFile(kosdaqStockDataList, "코스닥", "상승율순");
		 */
		Collections.sort(kospiNewHighPriceList, new DataSort.NameAscCompare());
		Collections.sort(kosdaqNewHighPriceList, new DataSort.NameAscCompare());
		Collections.sort(kospiNewLowPriceList, new DataSort.NameAscCompare());
		Collections.sort(kosdaqNewLowPriceList, new DataSort.NameAscCompare());

		newHighPriceList.addAll(kospiNewHighPriceList);
		newHighPriceList.addAll(kosdaqNewHighPriceList);
		newLowPriceList.addAll(kospiNewLowPriceList);
		newLowPriceList.addAll(kosdaqNewLowPriceList);

		StringBuilder html;
		if (newHighPriceList.size() > 0) {
			Collections.sort(newHighPriceList, new DataSort.NameAscCompare());

			html = createHtmlString(newHighPriceList, "코스닥,코스피", "신고가", "이름순");
			writeFile(html, "코스닥,코스피", "신고가", "이름순");
			// 네이버 블로그에 공유
			naverBlogLinkShare(html);
		}
		if (newLowPriceList.size() > 0) {
			Collections.sort(newLowPriceList, new DataSort.NameAscCompare());
			html = createHtmlString(newLowPriceList, "코스닥,코스피", "신저가", "이름순");
			writeFile(html, "코스닥,코스피", "신저가", "이름순");
			// 네이버 블로그에 공유
			naverBlogLinkShare(html);
		}

		if (kospiNewHighPriceList.size() > 0) {
			newLowHighPriceMap.put("코스피 신고가", kospiNewHighPriceList);
		}
		if (kosdaqNewHighPriceList.size() > 0) {
			newLowHighPriceMap.put("코스닥 신고가", kosdaqNewHighPriceList);
		}
		if (kospiNewLowPriceList.size() > 0) {
			newLowHighPriceMap.put("코스피 신저가", kospiNewLowPriceList);
		}
		if (kosdaqNewLowPriceList.size() > 0) {
			newLowHighPriceMap.put("코스닥 신저가", kosdaqNewLowPriceList);
		}
		if (newLowHighPriceMap.size() > 0) {
			writeFile(newLowHighPriceMap);
		}

	}

	public void readOne(String stockCode, String stockName, String marketGubun) {
		int cnt = 1;
		strStockCode = stockCode;
		strStockName = stockName;

		getStockInfo(cnt, strStockCode, strStockName, marketGubun);
	}

	public void readFile(String marketGubun, String strFileNameArg) {

		File f = new File(USER_HOME + "\\documents\\" + strFileNameArg);
		try {
			BufferedReader reader = new BufferedReader(new InputStreamReader(new FileInputStream(f), "UTF8"));

			String read = null;
			int cnt = 1;
			while ((read = reader.readLine()) != null) {
				logger.debug(cnt + "." + read);
				strStockCode = read.split("\t")[0];
				strStockName = read.split("\t")[1];
				logger.debug(strStockCode + "\t" + strStockName);

				if (strStockCode.length() != 6) {
					continue;
				}
				getStockInfo(cnt, strStockCode, strStockName, marketGubun);
				cnt++;
			}
			reader.close();
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		} catch (IOException e1) {
			e1.printStackTrace();
		} finally {
		}
	}

	public void getStockInfo(int cnt, String strStockCode, String strStockName, String marketGubun) {
		logger.debug("======================================================================");
		logger.debug(marketGubun + "." + cnt + "." + strStockCode + "." + strStockName);
		logger.debug("======================================================================");
		Document doc;
		StockVO stock = new StockVO();
		stock.setStockCode(strStockCode);
		stock.setStockName(strStockName);
		try {
			// 종합정보
			logger.debug("종합정보 http://finance.naver.com/item/main.nhn?code=" + strStockCode);
			doc = Jsoup.connect("http://finance.naver.com/item/main.nhn?code=" + strStockCode).get();
			// logger.debug("doc:"+doc);

			// 거래량 체크, 거래량이 0이면 빠져나간다.
			// Element tradeVolumeText = doc.select(".sp_txt9").get(0);
			String tradeVolumeText = doc.select(".sp_txt9").get(0).parent().child(1).child(0).text();
			logger.debug("tradeVolumeText:" + tradeVolumeText);

			Element new_totalinfo = doc.select(".new_totalinfo").get(0);
			Document new_totalinfo_doc = Jsoup.parse(new_totalinfo.html());
			Element blind = new_totalinfo_doc.select(".blind").get(0);
			Elements edds = blind.select("dd");

			String specialLetter = "";
			String sign = "";
			String curPrice = "";
			String varyPrice = "";
			String varyRatio = "";

			int iCurPrice = 0;
			int iVaryPrice = 0;

			for (int i = 0; i < edds.size(); i++) {
				Element dd = edds.get(i);
				String text = dd.text();

				if (text.startsWith("현재가")) {
					// logger.debug("data1:" + dd.text());
					text = text.replaceAll("플러스", "+");
					text = text.replaceAll("마이너스", "-");
					text = text.replaceAll("상승", "▲");
					text = text.replaceAll("하락", "▼");
					text = text.replaceAll("퍼센트", "%");

					String txts[] = text.split(" ");
					curPrice = txts[1];
					stock.setCurPrice(curPrice);
					stock.setiCurPrice(
							Integer.parseInt(StringUtils.defaultIfEmpty(stock.getCurPrice(), "0").replaceAll(",", "")));
					iCurPrice = stock.getiCurPrice();

					// 특수문자
					specialLetter = txts[3].replaceAll("보합", "");
					stock.setSpecialLetter(specialLetter);

					varyPrice = txts[4];
					stock.setVaryPrice(varyPrice);
					stock.setiVaryPrice(Integer
							.parseInt(StringUtils.defaultIfEmpty(stock.getVaryPrice(), "0").replaceAll(",", "")));
					iVaryPrice = stock.getiVaryPrice();

					// +- 부호
					sign = txts[5];
					stock.setSign(sign);
					// logger.debug("txts.length:" + txts.length);
					if (txts.length == 7) {
						stock.setVaryRatio(txts[5] + txts[6]);
					} else if (txts.length == 8) {
						stock.setVaryRatio(txts[5] + txts[6] + txts[7]);
					}
					varyRatio = stock.getVaryRatio();
					stock.setfVaryRatio(Float.parseFloat(varyRatio.replaceAll("%", "")));
					// logger.debug("상승률:" + stock.getVaryRatio());
				}
				logger.debug(text + " / " + text.split(" ")[0] + " " + text.split(" ")[1]);
				if (text.startsWith("전일가")) {
					stock.setBeforePrice(text.split(" ")[1]);
					stock.setiBeforePrice(Integer.parseInt(stock.getBeforePrice().replaceAll(",", "")));
				}
				if (text.startsWith("시가")) {
					stock.setStartPrice(text.split(" ")[1]);
					stock.setiStartPrice(Integer.parseInt(stock.getStartPrice().replaceAll(",", "")));
				}
				if (text.startsWith("고가")) {
					stock.setHighPrice(text.split(" ")[1]);
					stock.setiHighPrice(Integer.parseInt(stock.getHighPrice().replaceAll(",", "")));
				}
				if (text.startsWith("상한가")) {
					stock.setMaxPrice(text.split(" ")[1]);
					stock.setiMaxPrice(Integer.parseInt(stock.getMaxPrice().replaceAll(",", "")));
				}
				if (text.startsWith("저가")) {
					stock.setLowPrice(text.split(" ")[1]);
					stock.setiLowPrice(Integer.parseInt(stock.getLowPrice().replaceAll(",", "")));
				}
				if (text.startsWith("하한가")) {
					stock.setMinPrice(text.split(" ")[1]);
					stock.setiMinPrice(Integer.parseInt(stock.getMinPrice().replaceAll(",", "")));
				}
				if (text.startsWith("거래량")) {
					stock.setTradingVolume(text.split(" ")[1]);
					stock.setlTradingVolume(Integer.parseInt(stock.getTradingVolume().replaceAll(",", "")));
				}
				if (text.startsWith("거래대금") || text.startsWith("거래금액")) {
					stock.setTradingAmount(text.split(" ")[1].substring(0, text.split(" ")[1].indexOf("백만")));
					stock.setlTradingAmount(Integer
							.parseInt(StringUtils.defaultIfEmpty(stock.getTradingAmount().replaceAll(",", ""), "0")));
				}
			}

			String upDown = doc.select(".no_exday").get(0).select("em span").get(0).text();
			if (upDown.equals("상한가")) {
				specialLetter = "↑";
			} else if (upDown.equals("하한가")) {
				specialLetter = "↓";
			}
			stock.setSpecialLetter(specialLetter);

			// 종목분석-기업현황
			logger.debug("종목분석-기업현황 http://companyinfo.stock.naver.com/company/c1010001.aspx?cmp_cd=" + strStockCode);
			doc = Jsoup.connect("http://companyinfo.stock.naver.com/company/c1010001.aspx?cmp_cd=" + strStockCode)
					.get();
			// 시세 및 주주현황
			Element edd = doc.select("#cTB11").first();
			System.out.println("edd:" + edd);
			Elements trEls = edd.select("tr");
			Element tr1;
			String lowHighTxt = "";
			if (trEls.size() > 1) {
				tr1 = edd.select("tr").get(1);
				Elements tdEls = tr1.select("td");
				if (tdEls.size() > 0) {
					lowHighTxt = tdEls.text();
				}
			}

			System.out.println("lowHighTxt:" + lowHighTxt);
			if (lowHighTxt.equals("")) {
				return;
			}
			String lowHighTxtArray[] = lowHighTxt.split("/");
			System.out.println("lowHighTxtArray:" + lowHighTxtArray);

			// String curPrice = strTd0[0].substring(0, strTd0[0].indexOf("원"));
			String weeks52MaxPrice = lowHighTxtArray[0].replace("원", "").trim();
			String weeks52MinPrice = lowHighTxtArray[1].replace("원", "").trim();

			// stock.setCurPrice(curPrice);
			stock.setWeeks52MaxPrice(weeks52MaxPrice);
			stock.setWeeks52MinPrice(weeks52MinPrice);
			logger.debug("weeks52MaxPrice :" + stock.getWeeks52MaxPrice());
			logger.debug("weeks52MinPrice :" + stock.getWeeks52MinPrice());

			// curPrice = curPrice.replaceAll(",", "").trim();
			weeks52MaxPrice = weeks52MaxPrice.replaceAll(",", "").trim();
			weeks52MinPrice = weeks52MinPrice.replaceAll(",", "").trim();

			stock.setiWeeks52MaxPrice(Integer.parseInt(weeks52MaxPrice));
			stock.setiWeeks52MinPrice(Integer.parseInt(weeks52MinPrice));
			logger.debug("iWeeks52MaxPrice :" + stock.getiWeeks52MaxPrice());
			logger.debug("iWeeks52MinPrice :" + stock.getiWeeks52MinPrice());

			logger.debug("curPrice:" + curPrice);

			int iWeeks52MaxPrice = Integer.parseInt(weeks52MaxPrice);
			int iWeeks52MinPrice = Integer.parseInt(weeks52MinPrice);

			double upRatio = 0d;
			double downRatio = 0d;
			if (iWeeks52MinPrice < iCurPrice) {
				double d1 = iCurPrice - iWeeks52MinPrice;
				double d2 = d1 / iWeeks52MinPrice * 100;
				upRatio = Math.round(d2 * 100) / 100.0;
			} else if (iWeeks52MinPrice > iCurPrice) {
				logger.debug("신저가라네...");
				double d1 = iWeeks52MinPrice - iCurPrice;
				double d2 = d1 / iWeeks52MinPrice * 100;
				upRatio = -(Math.round(d2 * 100) / 100.0);
			}
			if (iWeeks52MaxPrice > iCurPrice) {
				double d1 = iWeeks52MaxPrice - iCurPrice;
				double d2 = d1 / iWeeks52MaxPrice * 100;
				downRatio = -(Math.round(d2 * 100) / 100.0);
			} else if (iWeeks52MaxPrice < iCurPrice) {
				logger.debug("신고가라네...");
				double d1 = iCurPrice - iWeeks52MaxPrice;
				double d2 = d1 / iWeeks52MaxPrice * 100;
				downRatio = Math.round(d2 * 100) / 100.0;
			}
			logger.debug("52주 신저가 대비 upRatio:" + upRatio + "% 상승");
			logger.debug("52주 신고가 대비 downRatio:" + downRatio + "% 하락");

			stock.setWeeks52NewHighPriceVsCurPriceDownRatio(downRatio);
			stock.setWeeks52NewLowPriceVsCurPriceUpRatio(upRatio);

			logger.debug("stock.getiHighPrice():" + stock.getiHighPrice() + " iWeeks52MaxPrice:" + iWeeks52MaxPrice
					+ ".고가 > 52주 최고가?" + (stock.getiHighPrice() > iWeeks52MaxPrice));
			logger.debug("stock.getiLowPrice():" + stock.getiLowPrice() + " iWeeks52MaxPrice:" + iWeeks52MinPrice
					+ ".저가 < 52주 최저가?" + (stock.getiLowPrice() < iWeeks52MinPrice));

			// 신고가
			if (stock.getiHighPrice() > iWeeks52MaxPrice) {
				stock.setWeeks52NewHighPrice(true);
				if (marketGubun.equals("P")) {
					kospiNewHighPriceList.add(stock);
					logger.debug(" kospiNewHighPriceList.size :" + kospiNewHighPriceList.size());
				} else {
					kosdaqNewHighPriceList.add(stock);
					logger.debug(" kosdaqNewHighPriceList.size :" + kosdaqNewHighPriceList.size());
				}
			}
			// 신저가
			// 최저가=0 제외
			if ((stock.getiLowPrice() != 0) && (stock.getiLowPrice() < iWeeks52MinPrice)) {
				stock.setWeeks52NewLowPrice(true);
				if (marketGubun.equals("P")) {
					kospiNewLowPriceList.add(stock);
					logger.debug(" kospiNewLowPriceList.size :" + kospiNewLowPriceList.size());
				} else {
					kosdaqNewLowPriceList.add(stock);
					logger.debug(" kosdaqNewLowPriceList.size :" + kosdaqNewLowPriceList.size());
				}
			}
			if (marketGubun.equals("P")) {
				kospiStockDataList.add(stock);
			} else {
				kosdaqStockDataList.add(stock);
			}
		} catch (IOException e) {
			logger.debug(e.getMessage());
		} catch (NumberFormatException e) {
			logger.debug(e.getMessage());
		}
	}

	public StringBuilder createHtmlString(List<StockVO> stockList, String stockMarketGubun, String lowHighGubun,
			String orderBy) {
		logger.debug("kospiKosdaqStockList.size :" + stockList.size());
		String strFileNameSuffix = "";
		if (lowHighGubun.equals("신고가")) {// 신고가
//			strFileNameSuffix = "52주 신저가 대비 상승율(" + orderBy + ")";
			strFileNameSuffix = "52주 " + lowHighGubun + "(" + orderBy + ")";
		} else if (lowHighGubun.equals("신저가")) {// 신저가
//			strFileNameSuffix = "52주 신고가 대비 하락율(" + orderBy + ")";
			strFileNameSuffix = "52주 " + lowHighGubun + " (" + orderBy + ")";
		}
		StringBuilder sb1 = new StringBuilder();
		sb1.append("<html lang='ko'>\r\n");
		sb1.append("<head>\r\n");
		// sb1.append("<meta http-equiv=\"Content-Type\"
		// content=\"text/html;charset=utf-8\">\r\n");
		sb1.append("<style>\r\n");
		sb1.append("    table {border:1px solid #aaaaaa;}\r\n");
		sb1.append("    td {border:1px solid #aaaaaa;}\r\n");
		sb1.append("</style>\r\n");
		sb1.append("</head>\r\n");
		sb1.append("<body>\r\n");
		sb1.append("\t<h2 id='title'>").append(strYmdDashBracket).append(" ").append(stockMarketGubun).append(" ")
				.append(strFileNameSuffix).append("</h2>");

		sb1.append("<table>\r\n");
		sb1.append("<tr>\r\n");
		sb1.append("<td style='background:#669900;color:#ffffff;text-align:center;font-size:12px;'>No.</td>\r\n");
		sb1.append("<td style='background:#669900;color:#ffffff;text-align:center;font-size:12px;'>종목명</td>\r\n");
		sb1.append("<td style='background:#669900;color:#ffffff;text-align:center;font-size:12px;'>현재가</td>\r\n");
		sb1.append("<td style='background:#669900;color:#ffffff;text-align:center;font-size:12px;'>전일대비</td>\r\n");
		sb1.append("<td style='background:#669900;color:#ffffff;text-align:center;font-size:12px;'>등락율</td>\r\n");
		sb1.append("<td style='background:#669900;color:#ffffff;text-align:center;font-size:12px;'>52주 최저가</td>\r\n");
		sb1.append("<td style='background:#669900;color:#ffffff;text-align:center;font-size:12px;'>52주 최고가</td>\r\n");
		sb1.append(
				"<td style='background:#669900;color:#ffffff;text-align:center;font-size:12px;'>최저가 대비 상승율</td>\r\n");
		sb1.append(
				"<td style='background:#669900;color:#ffffff;text-align:center;font-size:12px;'>최고가 대비 하락율</td>\r\n");
		sb1.append("</tr>\r\n");

		int cnt = 1;
		for (StockVO s : stockList) {
			logger.debug("s :" + s);
			if (s != null) {
				sb1.append("<tr>\r\n");
				String url = "http://finance.naver.com/item/main.nhn?code=" + s.getStockCode();
				sb1.append("<td>").append(cnt++).append("</td>\r\n");
				sb1.append("<td><a href='").append(url).append("' target='_sub'>").append(s.getStockName())
						.append("</a></td>\r\n");

				String specialLetter = StringUtils.defaultIfEmpty(s.getSpecialLetter(), "");
				String varyPrice = s.getVaryPrice();

				logger.debug("specialLetter+++>" + specialLetter);
				logger.debug("varyPrice+++>" + varyPrice);

				if (specialLetter.startsWith("↑") || specialLetter.startsWith("▲") || specialLetter.startsWith("+")) {
					sb1.append("<td style='text-align:right;color:red'>")
							.append(StringUtils.defaultIfEmpty(s.getCurPrice(), "")).append("</td>\r\n");
					sb1.append("<td style='text-align:right'><font color='red'>").append(specialLetter).append(" ")
							.append(varyPrice).append("</font></td>\r\n");
				} else if (specialLetter.startsWith("↓") || specialLetter.startsWith("▼")
						|| specialLetter.startsWith("-")) {
					sb1.append("<td style='text-align:right;color:blue'>")
							.append(StringUtils.defaultIfEmpty(s.getCurPrice(), "")).append("</td>\r\n");
					sb1.append("<td style='text-align:right'><font color='blue'>").append(specialLetter).append(" ")
							.append(varyPrice).append("</font></td>\r\n");
				} else {
					sb1.append("<td style='text-align:right;color:metal'>")
							.append(StringUtils.defaultIfEmpty(s.getCurPrice(), "")).append("</td>\r\n");
					sb1.append("<td style='text-align:right'>0</td>\r\n");
				}

				String varyRatio = StringUtils.defaultIfEmpty(s.getVaryRatio(), "");
				if (varyRatio.startsWith("+")) {
					sb1.append("<td style='text-align:right'><font color='red'>").append(varyRatio)
							.append("</font></td>\r\n");
				} else if (varyRatio.startsWith("-")) {
					sb1.append("<td style='text-align:right'><font color='blue'>").append(varyRatio)
							.append("</font></td>\r\n");
				} else {
					sb1.append("<td style='text-align:right'><font color='black'>").append(varyRatio)
							.append("</font></td>\r\n");
				}

				sb1.append("<td style='text-align:right'>").append(StringUtils.defaultString(s.getWeeks52MinPrice()))
						.append("</td>\r\n");
				sb1.append("<td style='text-align:right'>").append(StringUtils.defaultString(s.getWeeks52MaxPrice()))
						.append("</td>\r\n");

				sb1.append("<td style='text-align:right'>").append(s.getWeeks52NewLowPriceVsCurPriceUpRatio())
						.append("%").append("</td>\r\n");
				sb1.append("<td style='text-align:right'>").append(s.getWeeks52NewHighPriceVsCurPriceDownRatio())
						.append("%").append("</td>\r\n");

				sb1.append("</tr>\r\n");
			}
		}
		sb1.append("</table>\r\n");
		sb1.append("<br><br>\r\n");

		// 뉴스 첨부
		StringBuilder newsAddedStockList = StockUtil.getNews(stockList);
		// 증권명에 증권링크 생성
		StringBuilder stockTableAdded = StockUtil.stockLinkString(newsAddedStockList, stockList);
		sb1.append(stockTableAdded.toString());

		sb1.append("</body>\r\n");
		sb1.append("</html>\r\n");
		logger.debug(sb1.toString());
		return sb1;
	}

	public void writeFile(StringBuilder sb, String stockMarketGubun, String lowHighGubun, String orderBy) {
		String strFileNameSuffix = "";
		if (lowHighGubun.equals("신고가")) {// 신고가
//			strFileNameSuffix = "52주 신저가 대비 상승율(" + orderBy + ")";
			strFileNameSuffix = "52주 " + lowHighGubun + "(" + orderBy + ")";
		} else if (lowHighGubun.equals("신저가")) {// 신저가
//			strFileNameSuffix = "52주 신고가 대비 하락율(" + orderBy + ")";
			strFileNameSuffix = "52주 " + lowHighGubun + " (" + orderBy + ")";
		}
		strFileName = USER_HOME + "\\documents\\" + strYmdDashBracket + "_" + strHms + "_" + stockMarketGubun + "_"
				+ strFileNameSuffix + ".html";
		logger.debug("strFileName==>" + strFileName);
		FileUtil.fileWrite(strFileName, sb.toString());
	}

	public void writeFile(Map<String, List<StockVO>> newLowHighPriceMap) {
		StringBuilder sb1 = new StringBuilder();
		sb1.append("<html lang='ko'>\r\n");
		sb1.append("<head>\r\n");
		// sb1.append("<meta http-equiv=\"Content-Type\"
		// content=\"text/html;charset=utf-8\">\r\n");
		sb1.append("<style>\r\n");
		sb1.append("    table {border:1px solid #aaaaaa;}\r\n");
		sb1.append("    td {border:1px solid #aaaaaa;}\r\n");
		sb1.append("</style>\r\n");
		sb1.append("</head>\r\n");
		sb1.append("<body>\r\n");
		sb1.append("\t<h2 id='title'>").append(strYmdDashBracket).append(" " + "코스피,코스닥 신고,신저가").append("</h2>");

		Set keySet = newLowHighPriceMap.keySet();
		Iterator it = keySet.iterator();
		while (it.hasNext()) {
			String key = (String) it.next();
			List<StockVO> stockList = newLowHighPriceMap.get(key);

			sb1.append("\t<h2>").append(key).append("</h2>");
			sb1.append("<table>\r\n");
			sb1.append("<tr>\r\n");
			sb1.append("<td style='background:#669900;color:#ffffff;text-align:center;font-size:12px;'>No.</td>\r\n");
			sb1.append("<td style='background:#669900;color:#ffffff;text-align:center;font-size:12px;'>종목명</td>\r\n");
			if (key.contains("신저가")) {
				sb1.append(
						"<td style='background:#669900;color:#ffffff;text-align:center;font-size:12px;'>52주 최저가</td>\r\n");
			} else if (key.contains("신고가")) {
				sb1.append(
						"<td style='background:#669900;color:#ffffff;text-align:center;font-size:12px;'>52주 최고가</td>\r\n");
			}
			sb1.append("<td style='background:#669900;color:#ffffff;text-align:center;font-size:12px;'>현재가</td>\r\n");
			sb1.append("<td style='background:#669900;color:#ffffff;text-align:center;font-size:12px;'>전일대비</td>\r\n");
			sb1.append("<td style='background:#669900;color:#ffffff;text-align:center;font-size:12px;'>등락율</td>\r\n");
			if (key.contains("신저가")) {
				sb1.append(
						"<td style='background:#669900;color:#ffffff;text-align:center;font-size:12px;'>신저가</td>\r\n");
			} else if (key.contains("신고가")) {
				sb1.append(
						"<td style='background:#669900;color:#ffffff;text-align:center;font-size:12px;'>신고가</td>\r\n");
			}
			sb1.append("</tr>\r\n");

			int cnt = 1;
			for (StockVO s : stockList) {
				logger.debug("s :" + s);
				if (s != null) {
					sb1.append("<tr>\r\n");
					String url = "http://finance.naver.com/item/main.nhn?code=" + s.getStockCode();
					sb1.append("<td>").append(cnt++).append("</td>\r\n");
					sb1.append("<td><a href='").append(url).append("' target='_sub'>").append(s.getStockName())
							.append("</a></td>\r\n");

					if (key.contains("신저가")) {
						sb1.append("<td style='text-align:right'>").append(s.getWeeks52MinPrice()).append("</td>\r\n");
					} else if (key.contains("신고가")) {
						sb1.append("<td style='text-align:right'>").append(s.getWeeks52MaxPrice()).append("</td>\r\n");
					}

					String specialLetter = StringUtils.defaultIfEmpty(s.getSpecialLetter(), "");
					String varyPrice = s.getVaryPrice();

					logger.debug("specialLetter+++>" + specialLetter);
					logger.debug("varyPrice+++>" + varyPrice);

					if (specialLetter.startsWith("↑") || specialLetter.startsWith("▲")
							|| specialLetter.startsWith("+")) {
						sb1.append("<td style='text-align:right;color:red'>")
								.append(StringUtils.defaultIfEmpty(s.getCurPrice(), "")).append("</td>\r\n");
						sb1.append("<td style='text-align:right'><font color='red'>").append(specialLetter).append(" ")
								.append(varyPrice).append("</font></td>\r\n");
					} else if (specialLetter.startsWith("↓") || specialLetter.startsWith("▼")
							|| specialLetter.startsWith("-")) {
						sb1.append("<td style='text-align:right;color:blue'>")
								.append(StringUtils.defaultIfEmpty(s.getCurPrice(), "")).append("</td>\r\n");
						sb1.append("<td style='text-align:right'><font color='blue'>").append(specialLetter).append(" ")
								.append(varyPrice).append("</font></td>\r\n");
					} else {
						sb1.append("<td style='text-align:right;color:metal'>")
								.append(StringUtils.defaultIfEmpty(s.getCurPrice(), "")).append("</td>\r\n");
						sb1.append("<td style='text-align:right'>0</td>\r\n");
					}

					String varyRatio = StringUtils.defaultIfEmpty(s.getVaryRatio(), "");
					if (varyRatio.startsWith("+")) {
						sb1.append("<td style='text-align:right'><font color='red'>").append(varyRatio)
								.append("</font></td>\r\n");
					} else if (varyRatio.startsWith("-")) {
						sb1.append("<td style='text-align:right'><font color='blue'>").append(varyRatio)
								.append("</font></td>\r\n");
					} else {
						sb1.append("<td style='text-align:right'><font color='black'>").append(varyRatio)
								.append("</font></td>\r\n");
					}

					if (key.contains("신저가")) {
						sb1.append("<td style='text-align:right'>").append(s.getLowPrice()).append("</td>\r\n");
					} else if (key.contains("신고가")) {
						sb1.append("<td style='text-align:right'>").append(s.getHighPrice()).append("</td>\r\n");
					}

					sb1.append("</tr>\r\n");
				}
			}
			sb1.append("</table>\r\n");
			sb1.append("<br><br>\r\n");
		}

		logger.debug("keySet:" + keySet.toString());
		keySet = newLowHighPriceMap.keySet();
		logger.debug("keySet:" + keySet.toString());
		logger.debug("it:" + it.toString());
		it = keySet.iterator();
		while (it.hasNext()) {
			String key = (String) it.next();
			List<StockVO> stockList = newLowHighPriceMap.get(key);
			// 뉴스 첨부
			StringBuilder newsAddedStockList = StockUtil.getNews(stockList);
			// 증권명에 증권링크 생성
			StringBuilder stockTableAdded = StockUtil.stockLinkString(newsAddedStockList, stockList);
			sb1.append(stockTableAdded.toString());
		}

		sb1.append("</body>\r\n");
		sb1.append("</html>\r\n");
		strFileName = USER_HOME + "\\documents\\" + strYmdDashBracket + "_" + strHms + "_코스피,코스닥_52주_신고,신저가.html";
		logger.debug("strFileName==>" + strFileName);
		FileUtil.fileWrite(strFileName, sb1.toString());
	}

	public void readNews(List<StockVO> allStockList) {

		int cnt = 1;

		try {
			SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd HH.mm.ss.SSS", Locale.KOREAN);
			String strDate = sdf.format(new Date());

			FileWriter fw = new FileWriter(USER_HOME + "\\documents\\NewsTest." + strDate + ".html");
			StringBuilder sb1 = new StringBuilder();

			for (StockVO vo : allStockList) {
				strStockCode = vo.getStockCode();
				strStockName = vo.getStockName();

				logger.debug(cnt + "." + strStockCode + "." + strStockName);

				// 종합정보
				// http://finance.naver.com/item/news.nhn?code=246690
				logger.debug("http://finance.naver.com/item/news_news.nhn?code=" + strStockCode + "&page=");

				Document doc = Jsoup
						.connect("http://finance.naver.com/item/news_news.nhn?code=" + strStockCode + "&page=").get();
				// http://finance.naver.com/item/news_read.nhn?article_id=0002942514&office_id=011&code=246690&page=
				doc.select("script").remove();
				Element e1 = doc.select(".type5").get(0);

				Elements trs = e1.getElementsByTag("tr");

				for (int i = 0; i < trs.size(); i++) {
					Element tr = trs.get(i);

					Elements tds = tr.getElementsByTag("td");
					if (tds.size() < 3) {
						continue;
					}

					Element a1 = tr.getElementsByTag("a").first();
					Element source = tr.getElementsByTag("td").get(2);
					Element dayTime = tr.getElementsByTag("span").first();

					logger.debug("title:" + a1.html());
					logger.debug("href:" + a1.attr("href"));
					logger.debug("source:" + source.html());
					logger.debug("dayTime:" + dayTime.html());

					String strTitle = a1.html();
					String strLink = a1.attr("href");
					String strSource = source.html();
					String strDayTime = dayTime.html();
					String strYmd2 = strDayTime.substring(0, 10);
					int iYmd2 = Integer.parseInt(strYmd2.replaceAll("\\.", ""));

					// sb1.append("<h3>"+ strTitle +"</h3>\n");
					// sb1.append("<div>"+ strSource+" | "+ strDayTime
					// +"</div>\n");
					if (iYmd <= iYmd2) {
						// sb1.append("<h3>"+ strTitle +"</h3>\n");
						// sb1.append("<div>"+ strSource+" | "+ strDayTime
						// +"</div>\n");
						sb1.append("<h3><a href='http://finance.naver.com/item/main.nhn?code=").append(strStockCode)
								.append("'>").append(strStockName).append("(").append(strStockCode)
								.append(")</a></h3>\n");

						doc = Jsoup.connect("http://finance.naver.com" + strLink).get();
						Elements link_news_elements = doc.select(".link_news");
						if (link_news_elements != null) {
							link_news_elements.remove();
						}
						Elements naver_splugin = doc.select(".naver-splugin");
						logger.debug("naver_splugin:" + naver_splugin);
						if (naver_splugin != null) {
							naver_splugin.remove();
						}
						Element view = doc.select(".view").get(0);

						String strView = view.toString();
						strView = strView.replaceAll(strStockName,
								"<a href='http://finance.naver.com/item/main.nhn?code=" + strStockCode + "'>"
										+ strStockName + "</a>");

						sb1.append(strView);
						sb1.append("<br><br>\n");

						logger.debug("view:" + view);
					}
				}
			}

			logger.debug(sb1.toString());

			fw.write(sb1.toString());
			fw.close();

		} catch (IOException | NumberFormatException e) {
		}
	}

	// 네이버 블로그에 공유
	public void naverBlogLinkShare(StringBuilder html) {
		String strUrl = "";
		String strTitle = Jsoup.parse(html.toString()).select("h2#title").text();
		String categoryName = "164";// 신고,신저가
		StringBuilder contentSb = html;
		logger.debug("strBlogId:" + strBlogId);
		logger.debug("strNidAut:" + strNidAut);
		logger.debug("strNidSes:" + strNidSes);
		if (!StringUtils.defaultIfEmpty(strBlogId, "").equals("")
				&& !StringUtils.defaultIfEmpty(strNidAut, "").equals("")
				&& !StringUtils.defaultIfEmpty(strNidSes, "").equals("")) {
			NaverUtil.naverBlogLinkShare(strBlogId, strNidAut, strNidSes, strUrl, strTitle, categoryName, contentSb,
					null);
		}
	}
}
